### ISSUE TITLE
Request for PhotoView

### ISSUE THREAD

**Issue by jotierb** [chtaylo2/Roku-GooglePhotos#107]
I've been a fan of PhotoView but am disappointed to lose a crucial feature after the latest upgrade. During a slide show of classic paintings stored in a Google Drive folder, I could previously display the name of the file -- which is the name of the painting and painter -- by pressing PLAY or PAUSE. Now, after the upgrade, pressing those buttons just shows me the date of the file, not the name. Could you restore this option. It makes all the difference to me! Thanks for a great app. 

Best,
John

**Comment by chtaylo2** [comment]
This was fixed as part of https://github.com/chtaylo2/Roku-GooglePhotos/issues/91.

The release v2.1 is currently pending Roku approval. (~4-5 business days)

**Comment by jotierb** [comment]
That's great! I look forward to Roku's approval. Thank you for the reply --
and for the fix!

Gratefully,
John

**Comment by jotierb** [comment]
It's great to have the file names back! And the app is better than ever! I love being able to choose an album to be the screeensaver for my Roku -- I've now switched and made Photoview my screensaver because of that feature. And I've changed my rating in the Roku store to 5 stars -- all deserved! Thank you!
