### ISSUE TITLE
PhotoView Screensaver only accesses small subset of photos in Google Photos

### ISSUE THREAD

**Issue by brucealder** [chtaylo2/Roku-GooglePhotos#111]
I absolutely love PhotoView and think it serves a huge need on the Screensaver option (when serving up random photos from Google Photos). The only problem is that it accesses only a very small subset of photos (50? 100?), when I have a couple thousand photos. In addition, it accesses archived photos as well, would be nice if it skipped these.

I work at Google and may join the Photos team just to make this happen...because I've yet to see ANY application that simply serves up thousands of random photos as part of a screensaver offering.

If you could fix these two issues it would be revolutionary (the first is by far the highest priority):
1) Make PhotoView randomly access ALL photos in Google Photos...not just a subset
2) Make PhotoView access only the non-archived photos (or make this an on/off option if you want to give the user the choice).

Thanks!!
Bruce Alder

**Comment by arnoldsmyth** [comment]
You can now set it to view an album. I have this set up and add the photos that I want displayed. However I only have 125 or so in there at he moment. Are you saying that if you have thousands of photos in there that it only shows a subset of them?

**Comment by chtaylo2** [comment]
@brucealder glad you like the app, thanks for the feedback. If you work at Google, maybe you can help drive the Photos team to improve their API abilities. ;-)   Shared album support, +11,000 image pulling are the two short comings I commonly hear.

On your points: 
1.) If no albums are selected for screensaver, it'll randomly pull 5 albums + timeline album. Each one is limited to first 1000 items. >1000 items requires an additional API call which I have plans to build in, but haven't yet. Once the Screensaver starts, it doesn't make additional API calls. This was mostly to respect load on the API, but seems many folks are wanting this.

2.) Are the Archived photos it's showing part of an albums? Archiving only applies to the "Google Timeline Album". [This code](https://github.com/chtaylo2/Roku-GooglePhotos/blob/master/components/Slideshow/SlideshowHelper.brs#L168-L170) should prevent archived images showing when pulling from the primary album. I'll have to test that out some more.

**Comment by brucealder** [comment]
Hey Chris,
Great to hear from you...I've seriously looked for years for a screensaver
like PhotoView and as we just replaced our Android Player with a Roku, I
found it with PhotoView (originally I went to great lengths to side load
APKs on the Android Player in an effort to get the functionality that
PhotoView provides).

Per your points:
1a) On the number of albums, I need to pay closer attention to which albums
it's pulling (never set one), but that it would be pulling from 5 different
albums seems to match what I'm seeing.
1b) Should it really be pulling up to 6000 photos (1000 each from the
timeline album and the 5 additional albums)? That's a great capability. If
it's truly pulling 1000 items per album that seems like a lot more than I'm
actually seeing...I would have guessed it was pulling maybe ~100...or even
~50, I'll need to pay closer attention. If you *are* able to make changes
that enable it to pull more than 1000 photos that would be
fantastic...thanks in advance for considering this.
2) You're right, the archiving was done in the Timeline album...AND the
photos are part of a separate album. If you implement the logic to skip
archived photos in the Timeline album then, to take full advantage of this,
I'll ensure that the album with the archived photos is *not* selected as
part of screensaver.

On the Google Photos group front, I can definitely pass along Feature
Requests if you provide more details (assuming you haven't already
submitted these to the team)...it sounds like you have two:

   - Shared Album Support - I'm not sure on the specifics behind this, but
   it sounds like it would have some strong potential (especially if folks
   could post to a shared album and these would get picked up real time by
   PhotoView screensaver)
   - >11,000 image pulling - this would be huge...especially when you
   extend the API call to pull more than 1000 photos. If you want to provide
   details I can pass them along.

For reference, my personal email is brucealder6@gmail.com.

Btw, the Photos team is hiring (one of my employees interviewed, but it
wasn't a good match)...have you considered working at Google?
Bruce

**Comment by brucealder** [comment]
@arnold, Yes, you nailed it...I have thousands and it seems to pull ~50, or
maybe ~100 from several albums. I haven't specified an album, though, so
I'll play with that and see if it improves things.
Per Chris' post, it should pull 1000 per album (I would have guessed 50 to
100), so I need to pay close attention and confirm this.

**Comment by johnsko** [comment]
I've spent a bunch of time confirming that it pulls only first 1,000.  The workaround--putting photos in separate albums (and then selecting those albums)--is cumbersome but works well. An unfortunate limitation but still absolutely the best of many screensavers/slideshows I've tried on Roku.

**Comment by brucealder** [comment]
@johnsko - agreed completely, this is by far the best screensaver I've seen anywhere...even outside Roku

@chtaylo2 - I've created 5 albums with ~1000 photos each and it's working perfectly...no problems whatsoever...thanks for the great product. If you add an additional API call and can get more than 1000 photos please let us know, would love to use that option. Random question, would it be technically feasible to include videos in the albums and have the screensaver actually play those as it works it's way through the many photos? Thanks again...

**Comment by chtaylo2** [comment]
@brucealder / @johnsko - Agreed, the 1,000 limitation is on the Google API side per album. I could look at adding additional calls where total album count > 1000, but it's not there today. It does do this when viewing albums in the app w/ the use of paging feature. Selecting Page 1 - Page 11.

**Comment by EricB2301** [comment]
@chtaylo2 Have you been able to look at adding additional calls where total album count > 1000?  This would be a great benefit over the other aps available.
Thanks!

**Comment by caldude321** [comment]
Just wanted to say that this is a great project and product.  I love being able to add photos to my 'Screensaver' album and have them appear on the TV; I use the same album for digital photo frames and my phones screensaver.  I love having them all in sync.  My wife adds photos to the album too, but they're not displayed, would really like Shared album support, as others have mentioned.  I understand that it may be hard; google photos screensaver on android doesn't even do it.  

Thanks for the hard work.

**Comment by BethTimken** [comment]
Wonderful screensaver! 

I can't find where to select the albums I wish to have images drawn from. Would someone please direct me?

**Comment by chtaylo2** [comment]
@BethTimken --

To select a specific album for the screensaver:
-- "Roku Home" > Settings > Screensaver > select [PhotoView for Google Photos]
-- In the Custom Settings, select a linked account (if you have multiple)

**Comment by Rob-in-la** [comment]
If I try to select an album I get an error. It says "an error occurred in the handleGetAlbumSelection Code: 400 - the requested URL returned error: 400 bad request.

I'm running the built-in Roku on a Hisense TV. Any ideas?

**Comment by mikelmartin** [comment]
I am getting the 400 bad request error as well. I have been running the screen saver for months (love it btw) but it started not working, and then when I went into settings and tried to select an album I get the 400 error.

**Comment by BethTimken** [comment]
Wonderful screensaver but I am having exactly the same problem as mikelmartin. It's been about 2-4 days. I've deleted it and reinstalled it, with no improvement. 

The Roku PhotoView no longer works at all, instead the standard Roku screensaver comes on.

**Comment by Rob-in-la** [comment]
It looks like it's a known issue that Chris is hopefully working on. (See https://github.com/chtaylo2 ) 

It appears to stem from Google making a change to their photos API.  It's an amazing app and will hopefully be back online soon.

**Comment by kaleend101** [comment]
Hello all,

Could someone please guide me how to select a particular album for screensaver. I have my google account linked but it seems to be getting photos from all 25 albums instead of the 1 I want it to select from.

Thank You
