### ISSUE TITLE
Features request:  video repeat play and play next video

### ISSUE THREAD

**Issue by benlee124** [chtaylo2/Roku-GooglePhotos#113]
Hi,

Thanks for developing the app.  My daughter also loves seeing videos of her on TV. Now, it would make my life a lot easier if you can add the features to repeat playing the same video and/or play the next video in the directory.  Thanks for your time.

**Comment by chtaylo2** [comment]
Nice idea!  I’ll see what I can do

**Comment by chtaylo2** [comment]
Adding to release v2.2
