### ISSUE TITLE
Feature Request: Display "title" from file metadata

### ISSUE THREAD

**Issue by johnsko** [chtaylo2/Roku-GooglePhotos#114]
Would be nice to have option to have "title" field from file metadata displayed during slideshow.  Additional option would be to have title displayed and then fade after 50% of display interval, or appear after 50% of the display interval.  The 'appear after 50%' setting would be great for guessing about photo and then seeing answer.

**Comment by chtaylo2** [comment]
I had looked at meta data before and didn't see any title field. Have you seen one available via the API?

**Comment by johnsko** [comment]
I noticed that Google Photos (in Chrome browser) does a nice job of displaying the title field across the bottom of the image but I don't know if it's available through the API.

**Comment by chtaylo2** [comment]
This will be added as part of #117     The "Title" field is actually the "description" of the image. This will added as part of release v2.2
