### ISSUE TITLE
Feature Request: Filter based on "rating"

### ISSUE THREAD

**Issue by johnsko** [chtaylo2/Roku-GooglePhotos#115]
Would be great to be able to select for slideshow only those photos with a specified minimum "rating" in file metadata.

**Comment by chtaylo2** [comment]
@johnsko - I've looked around and unable to find where you can rate photos. I've only been able to find where you can mark a one as a favorite.  https://photos.google.com/.  Can you point me to this?

**Comment by chtaylo2** [comment]
@johnsko -- Thanks for the details. There is no rating information coming back over the API from Google. It's possible with the new API version they'll support this, unsure at this time.  I'll keep this open for now, pending the new API.

**Comment by chtaylo2** [comment]
No option for ratings appear in the new API. Unable to impliment
