### ISSUE TITLE
Feature Request: 4K/UHD support,  >1600 image size

### ISSUE THREAD

**Issue by andorardo** [chtaylo2/Roku-GooglePhotos#116]
On Roku Ultra the maximum resolution is limited to full HD, even when the app is displaying in 2160p mode.

Is this an intrinsic Roku limitation, or is there a way to show photos in full 4K/UHD?

**Comment by andorardo** [comment]
FWIW I tried replacing the `"1600"` resolution in with `"d"` in `Common.brs`, but it didn't fix the situation.

Is that because the app can't enter UHD mode, or because the picasa API is not providing the high resolution files?

**Comment by chtaylo2** [comment]
The size=1600 is what is pulled back when UHD is selected. If you see here ( https://developers.google.com/picasa-web/docs/3.0/reference ), the supported sizes are: ... 1280, 1440, 1600.    1600 being the highest.

The channel will auto-scale the images up to the full UHD size to fill the screen. I've played around with it in the past and it's possible to get >1600 back if the requested size is eliminated, but it introduces other issues if doing that.

I'll keep this Issue open and continue to investigate, but hope this clears up some of your questions.

**Comment by andorardo** [comment]
Oh, I see! I was hoping that this option:

> There is an additional size d which results in the <media:content> elements referencing the original uploaded photo, including all original Exif data. It is valid only for use with the imgmax query parameter.

would allow the full size to be pulled, but what you're saying is that _other_ problems arise in that case.

Those other issues, are they to do with Roku app support (not being able to display in UHD mode), or with this app in particular?

**Comment by chtaylo2** [comment]
It's not really a Roku or the an issue with the app, more of a limitation with the Google API.  I don't recall what issues I had in the past.  I'll need to look more into it

**Comment by chtaylo2** [comment]
@andorardo - I've added in a "Ultra High Definition" download option in beta and would like to see if you can test it. This new setting under Slideshow Resolution will pull back a /s2160/ size vs /s1600/ from Google. 

https://my.roku.com/add/CCZ2T2

Could you add the above channel and let me know if it solves or at least helps with the issue you are seeing?

Thanks

**Comment by chtaylo2** [comment]
Closing.
