### ISSUE TITLE
Feature Request: Display date (or additional data)

### ISSUE THREAD

**Issue by aeykaygee** [chtaylo2/Roku-GooglePhotos#117]
Display a date of the photo from metadata as an overlay.
Another interesting data to display is geographic location of the photo based on the embedded geo data.

**Comment by chtaylo2** [comment]
If you hit the up arrow as the slide show is playing, it'll show the date of the photo pulled from Google Photos. Unfortunately the data available from Google's API on each photo is somewhat limited. I don't believe I've ever seen geo-data sent back.

**Comment by chtaylo2** [comment]
Scope for this feature request will be the addition of the photo description added to the overlay. If additional Info is added in the Google Photo application, it will start to be displayed on the overlay.

Geodata is sent back, but only longitude and latitude. Not sure at this time how we would translate that to an actual location.

**Comment by chtaylo2** [comment]
Resolving this feature request. Addition of "Photo details" will be added in v2.2

**Comment by jimmyj352** [comment]
Hi, Chris - I'm new to PhotoView, but I'm loving it!  Did this functionality disappear with the new API?  I don't seem to see it in the settings anywhere.

**Comment by jimmyj352** [comment]
> Hi, Chris - I'm new to PhotoView, but I'm loving it! Did this functionality disappear with the new API? I don't seem to see it in the settings anywhere.

Never mind, I just realized that this is topic is for browsing for photos.  It would be nice to see the date overlayed on photos in the screensaver.  I'll post that as a new feature request.
