### ISSUE TITLE
Feature Request: Use filters on photos

### ISSUE THREAD

**Issue by aeykaygee** [chtaylo2/Roku-GooglePhotos#118]
When displaying pictures, (optionally) also apply a random filter to that photo. Choose the filter at runtime.

**Comment by chtaylo2** [comment]
@aeykaygee -- Thanks for the suggestion. This is out of scope of what this channel is intended for at this time. You could add filters to photos in Google Photos app and have them display, but we're focusing on pulling vs. modifications.
