### ISSUE TITLE
Thank you! Super awesome app!

### ISSUE THREAD

**Issue by aeykaygee** [chtaylo2/Roku-GooglePhotos#119]
Didn't realize this was recently updated and stumbled upon it almost accidentally. This is pretty much exactly what I was looking for so thank you for making the app. It's almost constantly running on our family TV thus making it a huge photo frame and my kids love it too!

I have already submitted some ideas and might play around with the code.

**Comment by chtaylo2** [comment]
Thanks for the comments!
