### ISSUE TITLE
Albums Not Appearing

### ISSUE THREAD

**Issue by shrowell** [chtaylo2/Roku-GooglePhotos#120]
The "My Albums" view is wildly inaccurate compared to the list of Albums that I have on Google Photos itself. Some albums I have created in the past are present, but they are interspersed with 'albums' that I did not create (not by the Google Photos Assistant); usually illogical groupings of photos with a title of the date of one of the photos (but not all photos in the group). Worse, recent albums that I have shared with relatives and friends via Google Photos, do not appear in PhotoView at all! You can see the individual photos in the "timeline" album but that's not what anyone wants.

I was hoping that the Roku/Google Photos/Photoview experience would be better than the dreadful iCloud Slideshow fiasco of Apple TVs, but so far the jury is out.

Any fix in sight?

Simon

**Comment by chtaylo2** [comment]
Have you reviewed the FAQ's in the app? There is a section explicitly on "Shared Albums".  Grouping which are displayed in "Albums" come directly from Google's API and should match what you see here: https://photos.google.com/u/1/albums

Again, Shared Albums will not show, it's not supported by Google and out of my control.

**Comment by shrowell** [comment]
Yes Chris - as per the faq, I am not trying to view a lot albums that have been shared with me but an album that I have shared with others. 
Photoview is not displaying all my own albums. As per my original post, nearly all albums appear along with some odd albums that have a date as a title and a few photos in them. Specifically an album I created a week or so ago with 180 pictures in it does not appear. It's it because some people have made comments about the photos which somehow changes the status of the album. Nobody else has added content.
Simon


Sent from my Verizon, Samsung Galaxy S9+ smartphone
-------- Original message --------From: Chris Taylor <notifications@github.com> Date: 5/31/18  2:36 PM  (GMT-05:00) To: chtaylo2/Roku-GooglePhotos <Roku-GooglePhotos@noreply.github.com> Cc: shrowell <simon.rowell@gmail.com>, Author <author@noreply.github.com> Subject: Re: [chtaylo2/Roku-GooglePhotos] Albums Not Appearing (#120) 
Have you reviewed the FAQ's in the app? There is a section explicitly on "Shared Albums".  Grouping which are displayed in "Albums" come directly from Google's API and should match what you see here: https://photos.google.com/u/1/albums
Again, Shared Albums will not show, it's not supported by Google and out of my control.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/chtaylo2/Roku-GooglePhotos/issues/120#issuecomment-393632773","url":"https://github.com/chtaylo2/Roku-GooglePhotos/issues/120#issuecomment-393632773","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/chtaylo2/Roku-GooglePhotos","title":"chtaylo2/Roku-GooglePhotos","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/chtaylo2/Roku-GooglePhotos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chtaylo2 in #120: Have you reviewed the FAQ's in the app? There is a section explicitly on \"Shared Albums\".  Grouping which are displayed in \"Albums\" come directly from Google's API and should match what you see here: https://photos.google.com/u/1/albums\r\n\r\nAgain, Shared Albums will not show, it's not supported by Google and out of my control. "}],"action":{"name":"View Issue","url":"https://github.com/chtaylo2/Roku-GooglePhotos/issues/120#issuecomment-393632773"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [chtaylo2/Roku-GooglePhotos] Albums Not Appearing (#120)",
"sections": [
{
"text": "",
"activityTitle": "**Chris Taylor**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@chtaylo2",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"chtaylo2/Roku-GooglePhotos\",\n\"issueId\": 120,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"chtaylo2/Roku-GooglePhotos\",\n\"issueId\": 120\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/chtaylo2/Roku-GooglePhotos/issues/120#issuecomment-393632773"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 341112379\n}"
}
],
"themeColor": "26292E"
}

**Comment by mtuman** [comment]
PhotoView shows my ARCHIVE ALBUM, which contains a lot of odd, unwanted images, and not my carefully edited CURRENT ALBUMS. Am I doing something wrong? Us there a way to fix this? Thanks, Chris

**Comment by chtaylo2** [comment]
@mtuman - I'm only aware of the ability to archive photos, not albums. Where are you seeing the ability to do this?  https://photos.google.com/albums is the web front end for albums on Google. If you click the three DOTS beside and select "Delete" it will delete that album, removing it from your account. .. and you will not see it on the Roku app.

**Comment by mtuman** [comment]
Chris. These are the photos I now see in PhotoView:
https://get.google.com/albumarchive/105245055429849927852

When I want to see the photos here:
https://photos.google.com/albums

Hope I am making sense. The photos under ALBUMARCHIVE are far more
disorganized, & not a place I edit - unlike those under ALBUMS. Hence, I am
now unable to use PhotoView.

Thanks, Chris

**Comment by rhaskett** [comment]
I'm running into a similar issue.  If I create a "shared album" it will not show even if I was the one that created it.   If I create an album and then share it it _will_ show though if the other person adds photos. But the photos added by the other person will not show.

I had to get the person to send me the files and add them myself before they would show.

**Comment by chtaylo2** [comment]
@rhaskett -- Please see the FAQ section. Shared albums is not supported by the Google Photos API. This is what you are seeing. We're hoping the new API will allow this, unclear.
