### ISSUE TITLE
Animation chunking

### ISSUE THREAD

**Issue by knetch** [chtaylo2/Roku-GooglePhotos#122]
After about 10 seconds, the screen pauses for every new picture. After a moment, the new picture pops up from the bottom, skipping a few frames. I have the screensaver set to multi scrolling photos and picked out about 30 albums. I don't remember this occurring until I chose a set of albums as opposed to none.

Roku 3 - 4230X

**Comment by chtaylo2** [comment]
@knetch -- This seems to be a bandwidth limitation or CPU processing limitation on the Roku 3. If you have 30 albums selected, that's 30 API calls it's performing while the photos are starting it display on the screen.  The API pulling & photo display are synchronous, so depending on CPU and/or bandwidth, this could be a bottom neck.  

Have you noticed if it starts to act normal after 3-4 minutes (After all API calls are completed) ?

**Comment by knetch** [comment]
No, it doesn't get better. I was thinking of adding a configuration for the
number of pictures but haven't gotten around to it.

**Comment by chtaylo2** [comment]
Closing this as it was in the previous version.
