### ISSUE TITLE
New setting to turn off banner

### ISSUE THREAD

**Issue by nmbarry** [chtaylo2/Roku-GooglePhotos#124]
Please create a setting that allows users to turn off the banner that displays across the bottom of all photos.  It's not displaying the correct photo date or file name and it blocks the photos themselves.

**Comment by chtaylo2** [comment]
This is already possible. When you click “pause” the date (according to Google will show). Click the OK or the Up/Down buttons to hide or show the banner.

**Comment by rewallac** [comment]
I am not seeing the banner or the photo date. Am I missing something??

**Comment by nmbarry** [comment]
![15296705553482095148044](https://user-images.githubusercontent.com/40323897/41776586-fe3b92ea-75ed-11e8-8aca-c9ac19725b89.jpg)
Please note the banner across the bottom of the attached photo. I would like the ability to turn this off completely so I can view the entire photo. I think the challenge I'm having is that I want to "click through" my photos at my pace, not as a slide show. So I'm using the left and right arrows to move from photo to photo. Usually I am sharing my photos with friends and family so I want to proceed through them at my own pace so I can describe some photos at length, and skip over others more quickly. I do now understand that I need to hit ok to make the banner disappear, but I'd personally prefer that it not show up at all. You can close this ticket since I'm perhaps in the minority of your users.
