### ISSUE TITLE
App is not displaying all of my albums, and displays individual photos in the albums thumbnails

### ISSUE THREAD

**Issue by nmbarry** [chtaylo2/Roku-GooglePhotos#125]
I understand from the FAQs that albums that were shared to me (by others) will not be displayed in this app, but I'm not seeing all of the albums I've created and shared TO others, or the albums I created and have not shared at all.  I can't figure out how exactly the "My Albums" page is deciding what to display in the scrolling thumbnails, but it seems to be individual photos in my collection interspersed with the occasional album.  With the understanding that the app can't display albums shared to me by others, what I want (and I assume others would as well?) is for it to display the albums exactly as I see them when I click on the Albums link on photos.google.com

**Comment by chtaylo2** [comment]
If you go to: https://photos.google.com/albums -- These are the same Albums which will show when clicking on the "My Albums" button. The thumbnail image that shows is a random photo from that album which the Google API chooses. Is this what you are seeing? You can see the exact API code pulled back here: https://picasaweb.google.com/data/feed/api/user/default?kind=album&v=3.0&fields=entry(title,gphoto:numphotos,gphoto:user,gphoto:id,media:group(media:description,media:thumbnail))&thumbsize=300

Your "Google Timeline Album" is all your photos which are found here: https://photos.google.com

Shared Album support is not in the current Google API, but hopefully the new API will allow this.

**Comment by nmbarry** [comment]
I'll be honest, I pretty much gave up on your app because it just didn't
seem to work with my photo library. I launched the app just now so I could
at least give you some feedback on this ticket.  When I click on the "My
Albums" icon on the main menu, I now get an error that says "An Error
Occured in 'handleRefreshToken'.  Code: 400 - The requested URL returned
error: 400 Bad Request"

Hope this helps.

Thanks,

Nancy
