### ISSUE TITLE
Feature request: Make it more obvious how to select the screensaver album.

### ISSUE THREAD

**Issue by jamestalmage** [chtaylo2/Roku-GooglePhotos#126]
First of all. Amazing work. I have been wanting something like this for years. Very happy to have found it.

I came here to ask to add a feature allowing me to select which Album was displayed on the Screensaver, but now I see that you've actually already implemented that. 

In my opinion, it should be a top level option in the UI "Select Screensaver Album" instead of hidden under the "Select User" option.

Again - great job.

**Comment by chtaylo2** [comment]
@jamestalmage - Thanks for the feedback!

**Comment by BethTimken** [comment]
I love this program, it's fabulous! I have an art blog and use it to display classical art works and contemporary art in our home. It is a beautiful way to display full screen fine art. 

My son set it up Google Photos screensaver for me, and now I am trying to put up my album of fall artwork. I just can't find where to select the albums. It doesn't seem to be on the Roku monitor under settings and our son doesn't remember where he found it, either.

I hope someone can tell me where I go to select the albums to display on Google Photos screensaver! Thanks in advance.

**Comment by chtaylo2** [comment]
Tagged for v2.3
