### ISSUE TITLE
Mismatch between displayed and actual # of photos in Timeline

### ISSUE THREAD

**Issue by LibraSun** [chtaylo2/Roku-GooglePhotos#127]
Very simply put, PhotoView's main screen displays "615" for the count of photos in my "Timeline" album, whereas it actually contains only "1" photo. To further illustrate the count mismatch issue, PhotoView had been displaying "623" before I visited photos.google.com and sent 8 photos from "Archive" to "Trash".

Hoping there's a way for PV or GP to sync this count accurately (as I pride myself on filing GP images into folders on Google Drive, leaving none in the "Google Photos" folder, leaving the count near "0" at all times). Reason: I don't want the people using Roku in my absence to have unfettered access to every photo I take while on the road!

NOTE: For the same reason, it would be NICE (probably already a Feature Request) to be able to limit PhotoView's access to certain Albums and no others, in a manner similar to how we can already pre-select the album(s) used by ScreenSaver!

**Comment by chtaylo2** [comment]
Known issue. This is due to removal of archived items in in the final view

**Comment by LibraSun** [comment]
On the off chance that further feedback would help isolate possible causes of this Known Issue, I took two screenshots to demonstrate the "count mismatch".

PhotoView welcome screen, incorrectly showing "44 photos" in Timeline:
https://photos.app.goo.gl/rEQasSnpGD8sfhec8

PhotoView album screen of Timeline (selected on previous screen), showing "2 photos":
https://photos.app.goo.gl/ptKJ8k6yHDoar9my7

NOTE: The latter is accurate; I currently have only two images in Google Photos proper.

**Comment by chtaylo2** [comment]
This issue should be resolved now with the newer Google API. Closing.
