### ISSUE TITLE
Do not automatically include images attached to email

### ISSUE THREAD

**Issue by LibraSun** [chtaylo2/Roku-GooglePhotos#128]
For me, this one's a showstopper: Yesterday, I sent an email to someone with a single photo attached. Lo and behold, that image suddenly began appearing today (July 5, 2018) in PhotoView, as an "Album" entitled "2018-07-04" containing a single image... the one I had attached to the outgoing email.

Granted, the image was originally sent to me via email yesterday, but having no reason to play with PhotoView at the time, I did not check to see whether it popped up there upon receipt, or upon my sending it back out as a Forward. Either way, this is totally unexpected (and highly unwelcome!) behavior for the app.

I get that it's "Google's fault" for passing this image via the API; I just cannot imagine WHY that is so!?!?

Sadly, there's just no way I can use a Roku app that will unexpectedly display non-vetted images. Period.

**Comment by chtaylo2** [comment]
I've done what you described above tons of times and I have never seen this happen, nor has anyone ever reported this. Go here: https://photos.google.com/albums and you will see the albums Google has for you.. and you can delete whatever you don't want..  I just again did what you described above and confirmed it does not create a new album, nor load it into my photos.  

Did you confirm this multiple times?

**Comment by LibraSun** [comment]
I will explore the situation further, but in the meantime wanted to clarify a bit: The image in question was originally emailed to me from another Google Photos user, and the email heading announced "Google user shared 1 photo with you". Prior to that, I had never seen the photo. Rather than download or save it, I simply Forwarded it to another GMail user.

I checked at the /albums link you suggested above, and can most definitely attest to my own Google Photos containing a single album (containing 65 items). In fact, that's the *only* album I ever wish to have appear in PhotoView, and anything else that gets included (like "Timeline" or "Profile") will naturally stand out like a sore thumb.

I'll investigate by asking someone to share another photo with me via Google Photos, then carefully document whether it shows up in PhotoView. Thanks, Chris, for some truly amazing work!! Luv the app.

**Comment by LibraSun** [comment]
UPDATE: To make sure I'm providing you complete information, I went to the Google Photos app on my mobile device, and noticed that the offending image DOES appear in "Photos" (under "July"). However, the image/filename does NOT appear under "Photos" when I check the Google Photos web page from my laptop's Chrome browser! And, as stated above, I have no Album in either listing/place that contains the offending photo.

I have no images in Google Photos _per se_; that is 0 images are listed in the Google Photos folder of Google Drive when viewed with a Web browser. Likewise, "No Items" appears when I check again using the Drive app on my smartphone. All this is as expected, since I just began testing out the GP app 2-3 days ago.

I'll report back if another Shared/Forwarded instance creates a phantom album in PhotoView. :-)

**Comment by LibraSun** [comment]
SUGGEST merge of this thread with "Shared Albums Won't Disappear #112" instead.

Because I just tested whether a 3rd party sharing Google Photos image with me (and me simply forwarding it to another GMail user) would cause it to appear anywhere (in my GP, in my Google Drive, in PhotoView, etc.) and the answer was *no*. So for now this remains a strange edge case.

**Comment by chtaylo2** [comment]
Closing thread
