### ISSUE TITLE
Not showing photos in a shared album that are contributed by second person

### ISSUE THREAD

**Issue by usar59** [chtaylo2/Roku-GooglePhotos#129]
Nice app. Thank you..
I have it working with an album nicely. I have shared the album with my wife and she can add photos to the album and they are then visible online.
These additional photos do not show in the slideshow..
My workaround is to download the additional photos and then add them myself to the album..
This could well be a google permissions issue or a setting that I missed...

thanks..

**Comment by chtaylo2** [comment]
Thanks for the feedback.  Unfortunately shared albums / photos not showing is an API limitation.  There is a section in FAQ's detailing this out. Hopefully that'll answer your questions around this.
