### ISSUE TITLE
Space Breaks Search

### ISSUE THREAD

**Issue by antgiant** [chtaylo2/Roku-GooglePhotos#130]
If the search contains a space it throws an error of 
"Error
An Error Occurred in handleGetSearch'. Code: -3 -
No URL set!”

By playing with the phone remote app for Roku I discovered that if the space is replaced with a + the search works and the + is treated as a space in the search.

So, I think a simple find and replace of space with + in the search string will fix this issue.

**Comment by chtaylo2** [comment]
Thanks for the bug report. Will get this added into v2.2

**Comment by antgiant** [comment]
Awesome! Thank you!

**Comment by chtaylo2** [comment]
Checked into development. Added to Release v2.2 . 

Closing bug report.
