### ISSUE TITLE
APPLICATION CURRENTLY HAVING API ISSUES -- Error 404 Not Found

### ISSUE THREAD

**Issue by EdLatorre** [chtaylo2/Roku-GooglePhotos#140]
handleGetAlbumSelection code 404

Albums not found. Used to work well. Maybe it was something I did in Google photos, as I created a few new albums, but my only issue is with this app.
Thanks

**Comment by chtaylo2** [comment]
Thanks.  Yes, I'm aware. Google changed something and now the pulling of albums is not working..  Looking into.

**Comment by chtaylo2** [comment]
It was a Google API issue, they fixed it this evening:  https://issuetracker.google.com/issues/112532192
