### ISSUE TITLE
Display corruption with Roku Premiere

### ISSUE THREAD

**Issue by hobbes1069** [chtaylo2/Roku-GooglePhotos#141]
I have a Roku Premiere 4K hooked up to a regular 1080p Vizio. PhotoView has been working well for a long time but a few weeks ago (per the kids) when the screensaver tried to start the display would get corrupted. The only solution was to hit the Netflix (or other quick access button because the menu was unusable) to break it out of the screensaver.

Using PhotoView directly seems to work but trying a Preview of the screensaver shows an error saying it can't start the preview.

Now when I try to reproduce the error it's working... FIgures.

**Comment by chtaylo2** [comment]
If it's any constellation, that has happened to me on a Roku Premiere connected to my 4K TV as well. This Roku player has the generic screensaver enabled. So I have seen this, but has no direct correlation to the PhotoView application.

**Comment by chtaylo2** [comment]
You might want to open a discussion on the Roku Forums around this issue. https://forums.roku.com/viewforum.php?f=28 .   I keep thinking i should take a photo of it when it happens.  Maybe next time.  :-)
