### ISSUE TITLE
Major API Upgrade: Move to new GooglePhotos Library API

### ISSUE THREAD

**Issue by chtaylo2** [chtaylo2/Roku-GooglePhotos#142]
Moving to GooglePhotos Library API. 
https://developers.google.com/photos/library/guides/overview

**Comment by bacall213** [comment]
When you make this change, please consider moving to the use of a read only OAuth scope:
https://www.googleapis.com/auth/photoslibrary.readonly

(more info at https://developers.google.com/photos/library/guides/authentication-authorization)

**Comment by chtaylo2** [comment]
That would be nice. It isn't available in the legacy API to restrict access.

**Comment by chtaylo2** [comment]
Currently blocked on this issue: https://issuetracker.google.com/issues/113342106

**Comment by cbandy** [comment]
If you'd like to see this feature, please star the Google issue above.

**Comment by bacall213** [comment]
Thanks, commented on and starred the bug.

**Comment by ravenbyron** [comment]
any chance we could have a "private channel version" that required long form login (ie typing user/pass/2fa) so if google doesn't come through by the time the depreciated api breaks again.  Also may be helpful for debugging etc...

**Comment by chtaylo2** [comment]
No, they don't allow username/password.  You can add this working version for now until Roku approves the channel: https://my.roku.com/add/LJCCCK

I have an idea how to get around the Google Photo blocking issue. Still trying to work through to confirm it'll work.
