### ISSUE TITLE
Viewing quaility of videos

### ISSUE THREAD

**Issue by yxngbands** [chtaylo2/Roku-GooglePhotos#145]
I don't know what's happening, but I would like to play up to 1080p videos using your app. I downloaded a 1080p video to test this out and when I watched it in the app, it appeared at 480p or so. I did the same with a 720p video and, it appeared at about the 480p-240p range. I would love if you could fix this. 

P.s. I did a comparison with a 4k monitor and a 4k TV. I played the same video on the two different screens and saw equivalent results. Also, I'm for sure this isn't the video and is the app because I have 60+ 1080p videos that don't show the correct resolution.

 1080p video: https://www.youtube.com/watch?v=6v2L2UGZJAM  
  
  4k video: https://www.youtube.com/watch?v=NQt8tV8b4ic

**Comment by chtaylo2** [comment]
Yes, this is a known issue. With the current GooglePhotos API, we can pull 480p videos back and Roku can play them. When we change that to the 720p or 1080p feed (Google doesn't offer a 4K feed), Roku devices fail to play the video. I spent weeks trying to get this to work.

I think it's a codec issue with the transcribing between Google and Roku. It is unfortunate, but out of our hands on fixing at this time. Google is working on a new GooglePhotos API which I'm holding my breath will fix this issue.

**Comment by yxngbands** [comment]
Okay. Thanks for your time.

**Comment by msridhar** [comment]
Thanks for the fantastic Roku app!  I wonder if it would be good to update the README / docs on the status of this video resolution problem?  I only found this explanation by searching closed issues but others may not think to do that.  Alternately this issue could be kept open with low priority, etc.

Happy to submit a doc PR if that'd be helpful.

**Comment by chtaylo2** [comment]
@msridhar -- Sure, feel free to create a PR if you'd like. Thanks

**Comment by msridhar** [comment]
Any suggestion on where to document this?  Maybe a new entry in the tips and tricks?
