### ISSUE TITLE
Displays only the photos I uploaded to a Shared Album (as opposed to those uploaded by others)

### ISSUE THREAD

**Issue by brucealder** [chtaylo2/Roku-GooglePhotos#147]
I created an album and shared it with others so everyone could upload (and they did). When selecting this album in PhotoView Screensaver it only shares the photos I uploaded, it doesn't share the photos uploaded by the roughly other 10 folks who contributed. 

Is there something I need to do to enable this capability? On the Google Photos front?

**Comment by chtaylo2** [comment]
Thanks for the feedback. Unfortunately shared albums / photos not showing is an API limitation. There is a section in FAQ's detailing this out. Hopefully that'll answer your questions around this.

The new Google Photos API allows this, however we're waiting on Google to introduce support for TV devices; no updates have been provided by them yet.
