### ISSUE TITLE
Roku-Google Photos albums recently out-of-sync with image order of online albums

### ISSUE THREAD

**Issue by BethTimken** [chtaylo2/Roku-GooglePhotos#149]
I used to be able to view my photos on Roku in the order I had arranged within the albums online, recently this has been changing.

On my newer albums, Roku-GooglePhotos disregards the the image order I arranged online and photos are displayed in chronological order. 

In my older albums, Roku-GooglePhotos does display the photo order I arranged. However, if I add photos to an older album, then my online arrangement of photos is ignored and only shows in chronological order.

My Slideshow Order is set at Album Order (default)

Note: I went to my old Roku Picasa program, and found the same problem there.

Thanks so much for this wonderful program I would love to get it showing the way it did previously!

**Comment by BethTimken** [comment]
Thank you for the directions.

• My Slideshow Order has already been set at "Album Order (default)".  The photos show chronologically, rather than my order in Google Photos. 

• When I try setting it on reverse Album Order, they appear in reverse chronological order.

I have uninstalled and reinstalled roku - GooglePhotos several times and reset the slideshow order to "Album Order." I also have deleted the Picasa screensaver. I still have the same problem.

What would you advise me to do?

**Comment by chtaylo2** [comment]
I’m guessing your looking at items in the Google Timeline album. You could
try creating a new album and add all your photos to it, and setup whatever
order you want.  The Roku app should then honor that order.

Every testing I’ve done indicates this works as designed.  Good luck.

**Comment by BethTimken** [comment]
Thank you for taking the time to answer my questions, Chris. You created a fabulous application, it is so generous of you to put it out there for everyone! I appear to have resolved the problem and I thought you'd like a follow-up for possible future reference.

My PhotoView album's orders were out of sync with online Google Photos due to one or both of the following reasons:

•  Changed dates on photos

•  lmages having been archived or sent to the trash from within an album. (Our son saw some online mentioning this)

I duplicated several albums -- the new albums now keep my set order on Photo View!

The fresh albums don't have the residual glitches that were created in the old albums due to my changing dates and/or trashing photos from within the album. 

Note: The albums that didn't work properly on PhotoView had blank spots in-place of some of my photos. The blank spots appeared in in both the album's 'Slideshow' and 'Browse Album' function (however the photo titles still showed). Also these album's slideshow would not keep going automatically -- when a blank image came up, the slideshow would stop and Roku changed to screensaver mode. 

(If you want, I can provide screenshots)

..........

All's well that ends well! I am now enjoying wonderful images on Roku do to your wonderful application. Thank you!
