### ISSUE TITLE
Google Photo album error code

### ISSUE THREAD

**Issue by sjsj69** [chtaylo2/Roku-GooglePhotos#150]
When I try to look at albums I get this error: "An error Occurred in 'handleGetAlbumList'. Code: 404- The requested URL returned error: 404 Not Found"

**Comment by chtaylo2** [comment]
@sjsj69 -- Are you seeing this with all albums or was this a single event? It's possible the GooglePhotos API was having issues. I've not been able to duplicate this issue.  

What's the full name of the album? Any special characters in it?
