### ISSUE TITLE
Photoview

### ISSUE THREAD

**Issue by tennisdennis** [chtaylo2/Roku-GooglePhotos#151]
When I opened PhotoView through our Roku this message came up: An error occurred in 'handleRefresh Token' . Code:400- the requested URL returned error:400 Bad Request."  I have no idea what any of this means.  Can you help me correct this error code so I can again view pictures?  It worked prior to whenever you did an update.

Thank you,
Dennis

**Comment by chtaylo2** [comment]
Dennis, There has not been a production update in 5 months. When was the last time it was working? The error you are showing is on the OAuth token refresh which happens every 180 minutes. I would recommend un-registering / registering to clear you account. If that doesn't work uninstall and reinstall the channel to remove any cache.

Do you have any special characters in your displayed name? Email address?


> On a side note about your other "Where is..." issue. Do not come here acting like you paid money for this channel and that we owe you anything. This channel is used by hundreds of thousands active users and was created / shared as a community offering. Now, if you want me to help you with the issue, answer the above questions and I'll respond when I'm able.

**Comment by chtaylo2** [comment]
Dennis -- None of your photos are stored in the PhotoView app, so unregistering/deleting will not delete the photos from GooglePhotos itself.

Two things to try:
1.) Unregister your account from the App and re-register. To do this, open the channel, goto Settings (Looks like a Gear Wheel) and second from the bottom "Remove account link from device". This will basically reset the channel. Then follow directions to re-register. 

2.) # 1  will most likely fix the issue. If not, you should remove the channel completely and re-add. To do this go to your home screen, select the PhotoView all and click the * (Star) button, then remove channel.   Then proceed to re-add the channel as you originally did. # 2 resets everything and you can then re-register.

I'll keep this "Issue" open for the time being, please circle back if one of these worked.

/Chris

**Comment by tennisdennis** [comment]
Thank you a second time, Chris.  I did the #1 fix and it worked.  You can close the ‘Issue’ now.  I’m going to keep your instructional email for any future problems.  Again sorry to have caused your any angst.

Dennis

**Comment by chtaylo2** [comment]
Glad you got it working.  Thanks
