### ISSUE TITLE
Beta/Devel. Roku Channel Can't Be Added

### ISSUE THREAD

**Issue by Poincare1** [chtaylo2/Roku-GooglePhotos#153]
When trying to add the beta/development private channel, Roku reports: 

The channel code provided is associated with a channel not available in your region.

I am in the USA. Is this only available for non-USA Roku users?

**Comment by chtaylo2** [comment]
There’s no Beta/Development channel. Just add the channel in the channel store as that’s the latest version. It should be available UNC all country’s.

**Comment by Poincare1** [comment]
There is a post on Reddit by Chtaylo2 ([here](https://www.reddit.com/r/Roku/comments/5q86tk/google_photos_roku_channel/)) that states a beta channel for this Google Photos Roku app is available. I am trying to add that channel since it seems to enable better support of 4K videos and 4K photo displaying on 4K TVs.

**Comment by chtaylo2** [comment]
That post was from a year ago. It’s been released into the channel store for a long time now.

**Comment by chtaylo2** [comment]
4K video is still not supported..Google API limitation.  It does support photos though
