### ISSUE TITLE
Feature Request: Support of high quality video during playback

### ISSUE THREAD

**Issue by chtaylo2** [chtaylo2/Roku-GooglePhotos#168]
Until recently only m18 (360p) videos were working.  m22 (720p) and m37 (1080p) appear to be working on Roku playback.  

Need to review and impliment if this works.

**Comment by chtaylo2** [comment]
De-prioritizing due to Google API change.

**Comment by DeltaAssault** [comment]
Any update on this? The app still only plays videos in 360p for me.

**Comment by chtaylo2** [comment]
@DeltaAssault -- The way we display videos is technically not even supported by Google.. It just happens to work. Still holding to see if they get a supported version of this working.

**Comment by chtaylo2** [comment]
This has been released.
