### ISSUE TITLE
An Error Occurred

### ISSUE THREAD

**Issue by davedogcaddy** [chtaylo2/Roku-GooglePhotos#170]
Noticed I was getting generic icons in place of my photos in the screensaver tonight. Additionally, When I try to view the albums I get this error:

"An Error Occurred in 'handleGetAlbumsList'. Code: 400 - The requested URL returned error: 400 Bad Request"

I tired removing/reinstalling/reauthorizing. No dice. Anyone else?

**Comment by kwitt86** [comment]
Yes this is happening to us too! I work in a group home with adults with developmental disabilities. We use this feature in our clients bedrooms on their Roku TVs. Their families (who can’t always visit as often as they like) add photos to google albums which shows on the client’s bedroom TVs. It brings them a lot of joy. Hoping this gets fixed soon! :)

**Comment by chtaylo2** [comment]
Known issue..  trying to fix: https://developers.google.com/picasa-web/docs/3.0/deprecation

**Comment by davedogcaddy** [comment]
Thanks! Fingers Crossed!

**Comment by chtaylo2** [comment]
Need everyones support, please post your support for this feature here: https://issuetracker.google.com/issues/113342106 .   Without it, this channel may no longer work as the old Picasa API is going away soon.

**Comment by chtaylo2** [comment]
Temporary change has been added to the channel and published. Waiting on Roku to approve it. See: https://developers.google.com/picasa-web/docs/3.0/deprecation

**Comment by chtaylo2** [comment]
Duplicate #172

**Comment by chtaylo2** [comment]
You can add this private channel until Roku approves the new version: https://my.roku.com/add/LJCCCK
