### ISSUE TITLE
400 ERROR -- API ISSUE

### ISSUE THREAD

**Issue by chtaylo2** [chtaylo2/Roku-GooglePhotos#171]
This is a known issue.. we are trying to fix: https://developers.google.com/picasa-web/docs/3.0/deprecation

**Comment by chtaylo2** [comment]
Temporary change has been added to the channel and published. Waiting on Roku to approve it. See: https://developers.google.com/picasa-web/docs/3.0/deprecation

**Comment by ptwilli1** [comment]
Hi Chris,

Great app. I started receiving this error last night on my Roku Ultra and Roku Streaming Stick which had been working for about a month since I bough them. Are you planning to migrate to the new Google Photos API? Thanks!

**Comment by chtaylo2** [comment]
@ptwilli1  -- please see here: https://github.com/chtaylo2/Roku-GooglePhotos/issues/172

**Comment by ptwilli1** [comment]
Done! Commented support but didn't see anyway to formally star, etc?

**Comment by synred** [comment]
I have this issue code 400 issue on roku too. It been going on for about 4 days. When will this be fixed? I gather there's nothing I can do, right? 

Google Photos seems fine on PC, but fails on roku. I tried reconnecting, but it wouldn't let me because I was already connected. Turning roku on an off did not work.

**Comment by chtaylo2** [comment]
Duplicate #172

**Comment by chtaylo2** [comment]
You can add this private channel until Roku approves the new version: https://my.roku.com/add/LJCCCK

**Comment by chtaylo2** [comment]
Update [01/21/2019 - 4:00 pm ET]: Channel version was approved. Pending publish by Roku.
Update [01/21/2019 - 5:30 pm ET]: Channel published. To force update: Roku Home > Settings > System > System Update.  This will download the latest version.
