### ISSUE TITLE
Photo view not working

### ISSUE THREAD

**Issue by ajbplay** [chtaylo2/Roku-GooglePhotos#173]
Please help when you have time.  The app currently states an error occurred in handlegetalbumlist code 400.  This just started today I have tried everything. Reset tv, uninstall reinstall app removed info from app re added nothing has solved the issue.

**Comment by chtaylo2** [comment]
Duplicate to #172, #171 , #170

**Comment by chtaylo2** [comment]
Update [01/21/2019 - 4:00 pm ET]: Channel version was approved. Pending publish by Roku.
Update [01/21/2019 - 5:30 pm ET]: Channel published. To force update: Roku Home > Settings > System > System Update.  This will download the latest version.
