### ISSUE TITLE
Error code 400 'handleGetAlbumList'

### ISSUE THREAD

**Issue by guyadam** [chtaylo2/Roku-GooglePhotos#174]
Can you help please help with this error, I won't let me view photos and the screensaver does not work.

**Comment by chtaylo2** [comment]
See this issue:  #172

**Comment by chtaylo2** [comment]
You can add this private channel until Roku approves the new version: https://my.roku.com/add/LJCCCK

**Comment by chtaylo2** [comment]
Update [01/21/2019 - 4:00 pm ET]: Channel version was approved. Pending publish by Roku.
Update [01/21/2019 - 5:30 pm ET]: Channel published. To force update: Roku Home > Settings > System > System Update.  This will download the latest version.
