### ISSUE TITLE
Cannot remove private channel

### ISSUE THREAD

**Issue by dogenzenji8** [chtaylo2/Roku-GooglePhotos#176]
As a workaround mentioned in issue #172, I installed the [private channel](https://my.roku.com/add/LJCCCK) and now I cannot remove it. Every time I try, even after a reboot and a factory reset, it times out with an error stating, "Could not remove 'PhotoView for Google Photos'. Please try again later."

**Comment by dogenzenji8** [comment]
Thanks for the confirmation. I hope the following additional information proves useful. Continuing to troubleshoot, I tried installing the private channel again to then see if the uninstall would work. Instead, the installation creates a duplicate app install which when queried using External Control API, shows a different app with almost the same app Id, and the same build number...

`<app id="133629_d939" subtype="rsga" type="appl" version="4.375.20190117">PhotoView for Google Photos</app>
<app id="133629" subtype="rsga" type="appl" version="4.375.20190117">PhotoView for Google Photos</app>`

I can uninstall the duplicate but the existing app, the one with app Id "133629_d939" remains with the same error.

**Comment by dogenzenji8** [comment]
I ended up deactivating my account, doing a factory reset on the Roku, then starting from scratch. This got rid of the channel. Thanks for looking into this anyway.

**Comment by kdaly132** [comment]
Same issue as above. I now have it twice as I tried to reinstall but cannot remove. Hoping to avoid doing the factory reset.

**Comment by chtaylo2** [comment]
Tryed this again today and seemed to work now. Very strange..
