### ISSUE TITLE
Error occurred in 'handleGetAlbumList' Code 400 bad request

### ISSUE THREAD

**Issue by hopstah** [chtaylo2/Roku-GooglePhotos#177]
I think this started when I upgraded to Google One but I could be wrong. My photos no longer display in the screensaver and I am unable to browse as well. I have unlinked and relinked my account but I still get this error. Thank you.

**Comment by chtaylo2** [comment]
See this issue: #172 .   
-> Update [01/21/2019 - 5:30 pm ET]: Channel published. To force update: Roku Home > Settings > System > System Update. This will download the latest version.
