### ISSUE TITLE
When video screensaver?

### ISSUE THREAD

**Issue by nancysl19** [chtaylo2/Roku-GooglePhotos#180]
Dear Chris:

     When will video screensavers be available?  I have uploaded a beautiful aquarium video to Google Photos which I would like to be my screensaver.

Thanks,
Nancy S. Lyons

**Comment by chtaylo2** [comment]
I'm sorry Nancy, the Roku device does not allow video playback in screensavers today. This has been a request in the past and will be implemented if/when this is ever allowed.

Thanks
