### ISSUE TITLE
I just installed Photoview. None of my photos will display, either thumbnails or images. 

### ISSUE THREAD

**Issue by gregsfalco** [chtaylo2/Roku-GooglePhotos#185]
My account linked just fine. But no photos will display. When the Screensaver starts, it shows a black screen. When I pause the Screensaver, it displays the name of the image that should be on the screen, and it displays the number of the image that should be displayed (for example, 1 of 50). If I wait a while and pause it again, it displays the next photo's number (for example, 2 of 50).

**Comment by gregsfalco** [comment]
Super excited to find this app. Super disappointing that it's not displaying anything.

**Comment by chtaylo2** [comment]
Over the threshold of photo downloads for the day.  Today was the first day the new API went live... So we're negotiating with Google on our quota. Try back tomorrow.

**Comment by neurolizer** [comment]
May the negotiations be swift and in your favor! Hoping to use PhotoView for a birthday party slideshow tomorrow :)

**Comment by johnsko** [comment]
Glad to see you moving to new API.  Will be patient as you work through issues.  Experience so far: prompted by Roku displaying default screensaver, discovered you had made change and re-linked device; noticed that all settings preserved except album selection; was able to browse albums and photos within from app and screensaver functioned as expected; then, after multiple hours, got "screensaver timed out"; after attempting to force re-download by browsing app (which failed), screensaver loads black image.  disturbing that quota applied to app rather than to linked accounts individually.  my tv would be far less valuable without PhotoView's screensaver.  hoping for the best.  thanks for your passionate commitment.

**Comment by bcerve** [comment]
Chris, thanks much for the continued development. We were using PhotoView to present slides around our church campus until a few months ago when Google changed the API. We switched to another photo screensaver app. We have been experiencing stability issues with the other app “channel”. Just curious if you think we should hold off on switching back to PhotoView for now until you get the quota issues worked out? We really appreciate PhotoView and thank you for developing on the new API.

**Comment by harleywinn** [comment]
So it's been over a week now and, clearly, no progress has been made on negotiating your 'quota'. Why you decided to start the negotiations _after_ you went to production is beyond my comprehension. We have a large number of roku devices using the photoview app to display images around campus. We will be switching all of them to Google Chromecast in light of this ridiculous outage.

**Comment by cbandy** [comment]
![free](https://i.gifer.com/GQmQ.gif)

**Comment by chtaylo2** [comment]
@gregsfalco / @neurolizer -- the quota issue seems to be under control at the moment. Let me know if you see differently. 

@johnsko -- Thanks for your feedback. Please see here on the screensaver timeout ( #190 )

@bcerve -- Thanks for your feedback. This will be the first weekend of the increased quota, so still monitoring as we get the most usage on the weekend..so we'll see.  There is a current time limit on the screensaver (4 hours) and in app display (12 hours). I hope to change this, see this thread: #190 .

**Comment by johnsko** [comment]
Hey Chris,

I appreciate that this is volunteer work (and it offends me to see others being unappreciative, even insulting).

I get huge personal enjoyment from having the screensaver running on my big tv as I see it every time I glance away from my computer monitor. Sometimes I sit down intending to watch Netflix but while I’m thinking about what series I’m behind in, I just get lost in the memories flashing by and realize that 20 minutes have gone by.

This is all to say, 1) thanks, 2) I hope you can fix the timeout, and 3) can I make a donation as a sign of appreciation?

John

**Comment by neurolizer** [comment]
Worked great for me this weekend, thank you for such an awesome product :)

**Comment by dbgarlisch** [comment]
Perfect response.

BTW, just made a donation to say thanks for all your efforts.

**Comment by chtaylo2** [comment]
@dbgarlisch  -- Thanks!

@johnsko -- Thanks for the comments. I have this page setup for donations, http://www.roku-photoview.com/donations/ .  Thank you in advance! 

@harleywinn -- Thanks for your comments, happy to see you go. Here are some coupons - https://www.retailmenot.com/coupons/google .
