### ISSUE TITLE
PhotoView for Google Photos will not stay registered

### ISSUE THREAD

**Issue by Stevewiner** [chtaylo2/Roku-GooglePhotos#189]
I have installed and registered the channel/app and after leaving the channel for about an hour or more and returning I am forced to re-register. I have also removed and reinstalled the app but the problem persists. 

Please provide instructions how this problem can be eliminated.

**Comment by chtaylo2** [comment]
I’ve seen this a couple times as well. The refresh token Google provides when you register doesn’t allow renewal in random cases. I haven’t seen a pattern but try reregistering a few times, and you should get there.

I’ll see if there’s an open bug report at Google and will try to report it.

Thanks

**Comment by Stevewiner** [comment]
Chris,

Thank you for your response.

I have tried your suggestion and unfortunately the problem persists. Initially it appears to work but after a few hours the same Roku re-register the channel/app message appears.

Steve

Please consider the environment before printing this e-mail

**Comment by zaggner** [comment]
I just installed the app today and am experiencing the same problem. I've had to reregister 4 times today so far.

**Comment by Stevewiner** [comment]
Chris,

The problem has not abated no matter how many times I re-register. Have you received a response from Google or did you see a post about this problem by Google's Tech Support?  

Thanks

**Comment by chtaylo2** [comment]
@Stevewiner - No, i wouldn't expect anything from them fast.  This has worked in the past for me:

1. Goto: https://myaccount.google.com/security-checkup/3 -> "Show Others", and revoke anything related to "PhotoVIew".
2. Give it a few hours and then come back into the PhotoView channel
3. On the Main Menu with the 5 icons, key this sequence to clear the app: UP, UP, UP, UP, UP, options (*), options (*), play, play, play
4. Re-register

If it works after 60 minutes, you're all good.   Please post back here if this works.

**Comment by zaggner** [comment]
Chris,

Just to let you know that I am experiencing this problem with a completely separate app where it is deauthorizing the Google Photo sharing after a short amount of time so it's not just your app.

BTW, terrific app you have here.  It works wonderfully for exactly what it was designed for and based on the information I've gleaned it sounds like you put a lot of work into getting to converted over to the new Google API.  Just wanted to say thanks!

**Comment by Stevewiner** [comment]
Chris,

Sorry to say I followed your instructions and it did not work. Like all other attempts initially it looked like was working but when I went back to the app about 24 hours later it was back to having to re-register.

Steve

On Mar 29, 2019, at 6:09 PM, Chris Taylor <notifications@github.com<mailto:notifications@github.com>> wrote:


@Stevewiner<https://github.com/Stevewiner> - No, i wouldn't expect anything from them fast. This has worked in the past for me:

  1.  Goto: https://myaccount.google.com/security-checkup/3 -> "Show Others", and revoke anything related to "PhotoVIew".
  2.  Give it a few hours and then come back into the PhotoView channel
  3.  On the Main Menu with the 5 icons, key this sequence to clear the app: UP, UP, UP, UP, UP, options (), options (), play, play, play
  4.  Re-register

If it works after 60 minutes, you're all good. Please post back here if this works.

**Comment by andrewbd** [comment]
Hi Chris, I'm sure you're working tireless on this, but I am having this issue on two devices. I've tried multiple times to reregister and followed your instructions, but still have the problem. Just wanted to post here and hopefully bump this thread up. 

Thanks for your great app. We use it everyday in our office, and this is the first issue we've had with it.

**Comment by davidwhutton** [comment]
Love the app, but unfortunately I'm having the same problem. My registration seems to expire almost immediately.

**Comment by KGart0n** [comment]
Love the app, but unfortunately I'm having the same problem.  Constantly having to re-register. Cannot use Photoview!

**Comment by samhande** [comment]
Same here, love the app but constantly need to register. Tried revoking Google token, that did not work any better.

**Comment by chtaylo2** [comment]
**UPDATE:**  Some users have been seeing their access tokens expire prematurely. This should now be fixed! If you are seeing this issue, please unregister your Google Photos account from this device and re-register.

Thanks for your patience.


** So what happened?** . Google must have recently changed their refresh token length (from 50) to 102. This was an unexpected change and broke some functions. We limit the size of VARCHAR fields for security and were only capturing part of the refresh token causing it to not re-issue when needed. 

Please try to re-register, should be good now.

**Comment by davidwhutton** [comment]
This seems to have fixed the problem for me.
Thank you Chris!
