### ISSUE TITLE
Bug report: Two photos in album breaks the album loop

### ISSUE THREAD

**Issue by jimgub** [chtaylo2/Roku-GooglePhotos#191]
Chris,
first off, you have developed a great app. Thanks for that.
I am having troubles on two different Roku's to get the screensaver to loop. For now I just have two images in my Google Photos Library and the screensaver cycles thru and then just goes back to Image #1. I have tried everything. I assume is capable of looping?  Any suggestions?

**Comment by chtaylo2** [comment]
@jimgub -- Could you please take a short video of this happening and email it to me?
rokuphotoview@gmail.com . (Make sure you tag the subject with "Issue #191")

Yes, looping of two images shouldn't be any issue. I'll try to duplicate it, but please send over a video.

thx

**Comment by chtaylo2** [comment]
Disregard on the video, I see the issue.  It's a bug. Actually if you have 1 or 3+ it works fine.  Will look into.

**Comment by jimgub** [comment]
Hi Chris
sorry to bother you… new problem today… getting 429 Too Many requests error… can’t display any albums or images… seems like it could be a “bigger” problem?

thanks for any update

Jim

**Comment by chtaylo2** [comment]
@jimgub - It's a system wide google api issue, unrelated to the application.

**Comment by jimgub** [comment]
Thanks for the reply! I guess that means we wait for them to fix?? Do you have any insight into how long that could take?  Thanks for any insight. We use your app at a restaurant to display images. And not having it work hurts.

**Comment by chtaylo2** [comment]
Fix has been implemented and will roll out with release 3.3
