### ISSUE TITLE
Bug: Random Photos reverting to Chronological Order - OnSearchEvents

### ISSUE THREAD

**Issue by timrit** [chtaylo2/Roku-GooglePhotos#203]
Using the latest version (5.203 build 20190319).  Seems to be working great except for one issue(feature?) that seems to crop up after the slideshow has been running for a while.  After 15min or so, it changes from random order to chronological order.   I am running with the following screensaver settings:
-High Def 720p
-Fading w/ background blur
-10 sec delay
-Random order
-Week in History (love this feature!!!)

Thanks Chris, keep up the good work!

**Comment by Rob-in-la** [comment]
I noticed this same problem yesterday before the app completed died (described on another issue.)

**Comment by chtaylo2** [comment]
Confirmed finding. Only impacts doGetSearch function. Normal albums are not impacted.

**Comment by chtaylo2** [comment]
Completed change. Will be pushed soon with v3.2 release
