### ISSUE TITLE
Enhancement: Google no longer provides NAME 

### ISSUE THREAD

**Issue by chtaylo2** [chtaylo2/Roku-GooglePhotos#207]
Google no only provides EMAIL ADDRESS and PHOTO. No longer a name.

{
    "sub": "<HIDDEN>",
    "picture": "https://lh3.googleusercontent.com/<HIDDEN>/photo.jpg",
    "email": "<hidden>@gmail.com",
    "email_verified": true
}

**Comment by cbandy** [comment]
This seems reasonable to me. iiuc, to get name one should request `profile` scope.

**Comment by chtaylo2** [comment]
Based on @cbandy comments, reviewed the API usage again and will revert this change. Also added the **userinfo.profile** to the requested scope going forward.
