### ISSUE TITLE
Volume on videos too low?

### ISSUE THREAD

**Issue by DeltaAssault** [chtaylo2/Roku-GooglePhotos#219]
I've found that the volume level on videos is really low. I have to crank up the volume to max on my TV just to hear dialogue. This isn't a problem when I'm streaming videos directly from my laptop to the TV through HDMI.

**Comment by chtaylo2** [comment]
@DeltaAssault - I haven't been able to duplicate this. However, even so, we have no choice on the volume setting in the application itself. This is all part of the encoding from Google and how Roku decodes the video.
