### ISSUE TITLE
Photoview quit working after first use on a TCL Roku TV

### ISSUE THREAD

**Issue by Airhog** [chtaylo2/Roku-GooglePhotos#221]
I downloaded and installed the Photoview channel on my TCL Roku TV a few days ago. The app was able to stream pictures from my Google Photos account perfectly the very first time I used this app. The next time I tried to use this app I was unable to view any of my Google Photos in any of my albums. I have uninstalled and reinstalled the Photoview channel several time with no luck. Does anyone have a solution for this problem? I love the interface for the app but that doesn't really matter if the app does not work. Any help would be greatly appreciated. Thanks.

**Comment by chtaylo2** [comment]
@Airhog - I don't have a TCL Roku TV to test the app on, so I'm not able to troubleshoot. Can you Open the app, go to main menu (Where it shows all 5 icons across the screen) and press: UP, UP, UP, UP, UP, OPTIONS (*), OPTIONS (*), PLAY, PLAY, PLAY

This will reset the PhotoView app settings. Once you re-register, see if you are able to duplicate the errors. If you continue to see the errors, could you please take a short video and email me at: rokuphotoview@gmail.com ?

Thanks
Chris

**Comment by Airhog** [comment]
Well……I have already reset the app with no luck. The weird thing is that is worked the very first time flawlessly but the next time I tried to scroll through pictures is did not work. Could this problem be unique to the Roku hardware on the TCL TV?

 

Anthony

**Comment by aggie45** [comment]
I’m having the same issue.  Everything seems to be set up correctly but all of the photos appear blank.  I can see the date/time, just not the photos.  Having the same problem with 2 separate google accounts and on a TCL TV with Roku built in as well as a Roku box on an LG TV.

**Comment by chtaylo2** [comment]
I've attempted this on a TCL TV w/Roku and was not able to re-produce the issue

**Comment by andreaordodi** [comment]
Does not work on my TCL Roku TV either it's all set up but the screensaver never comes on unless I go to the app and play it
