### ISSUE TITLE
Duplicate photos on media pages

### ISSUE THREAD

**Issue by Pearson2010** [chtaylo2/Roku-GooglePhotos#222]
Each Media page displays the same photos over and over again. For example one of the options is 653 photos on 7 media pages, each media page has about 20-30 photos displayed over and over again so instead of 653 different photos its about say 200-250. I'm not the best at tech stuff so i hope i have worded this so it's understandable for you. Thanks

**Comment by chtaylo2** [comment]
@Pearson2010 - Have many albums used for testing and I've never seen or heard any others reporting this. Is this an Album or the "Google Photos Library" selection? What does it look like if you view the same album on https://photos.google.com.

Can you take some photos showing this duplication and email me?  rokuphotoview@gmail.com

**Comment by chtaylo2** [comment]
Closing issue.
