### ISSUE TITLE
Feature Request: Option to pull photos from USB/SD or local PC/NAS

### ISSUE THREAD

**Issue by wred2** [chtaylo2/Roku-GooglePhotos#225]
This is by far the best channel for a screen saver I have tried. It seems though with the time limitation imposed by Google, that an option to pull photos from an USB/SD device if available, or from a local PC/NAS would solve the issue for a lot of people.

One other request - can the program stop pulling photos if the TV is turned off, i.e. save bandwidth.

Thanks

**Comment by chtaylo2** [comment]
@wred2 - USB/SD has been a request prior, however it not really the intent of this channel. I'm not ruling it out, but I wouldn't expect it anytime soon. 

RE: Turning the TV off, some newer TV's support this through HDMI-CEC (Consumer Electronics Control). Roku just started supporting it recently, but was never an option in the past. I hope to get this implemented, as it would bring in a number of benefits for those who support it. Stay tuned!

**Comment by chtaylo2** [comment]
Will not be proceeding with USB/NAS request as a feature for this channel per above comment.
