### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by dwsscs** [chtaylo2/Roku-GooglePhotos#236]
Can the timers be turned off to do infinite play on the slideshows?

**Comment by chtaylo2** [comment]
Not today. See here: #190

**Comment by dwsscs** [comment]
Is there any way to have the app restart and play the slideshow every 11 hours or so to address the limit from google?

Sent from my iPhone

On Jul 21, 2019, at 10:42 AM, Chris Taylor <notifications@github.com<mailto:notifications@github.com>> wrote:


Not today. See here: #190<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchtaylo2%2FRoku-GooglePhotos%2Fissues%2F190&data=02%7C01%7C%7C2fbbe71427544f2dbd8808d70df20c65%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636993205543132128&sdata=ofZ1jfgMymTWG4pMDHTu5L6gQvQrqnt44%2BFB8v7P%2F8E%3D&reserved=0>
