### ISSUE TITLE
OLED Screen Burn-in

### ISSUE THREAD

**Issue by creira** [chtaylo2/Roku-GooglePhotos#241]
Hello,  I would love to use your screensaver on an OLED TV, however, there seems to be reported issues with static logos creating burn-in after a few hours of constant display.  Has it ever been considered to have the Photo View logo move from one corner to another occasionally to help avoid burn-in?

**Comment by chtaylo2** [comment]
@creira - Where are you seeing reported issue around burn-in?

The small logo you see on the screensaver will move between bottom and top of the screen every 20 minutes. At that 20 minute mark the pixels are reset over a black background to prevent burn-in.

You can see that here: https://github.com/chtaylo2/Roku-GooglePhotos/blob/master/components/Slideshow/DisplayPhotos/DisplayPhotos.xml#L252-L256
