### ISSUE TITLE
Bug: Roku TV's having HDMI-CEC Issues - (Issues with screensaver)

### ISSUE THREAD

**Issue by bmorenico** [chtaylo2/Roku-GooglePhotos#242]
I've been using the app happily for years. In the last two days, when it would go to the screensaver, it only displays one photo and says screensaver paused. It does this every time. I've uninstalled and reinstalled and the issue remains.

Probably related, when I do a slideshow, it starts by saying slideshow paused as well, but I can get it to go to the next slide unlike the screensaver.

Thanks

**Comment by chtaylo2** [comment]
@bmorenico - Few questions.

1.) I'm assuming your TV set is powered off when you're starting the slide show, can you confirm?
2.) What type of device do you have? Both Roku Model and TV Model.
3.) When you hit 'Continue' on the paused slideshow, does it pause again later on by itself?
4.) With the slideshow playing and you switch off your TV set, does it pause again?

**Comment by bmorenico** [comment]
I am using the TCL with Roku built in. I have three of them, models
TCL 55S517 and TCL 65S517 and both have the same issue.

The TV is on when the screensaver starts. I have it set up where the
screensaver comes on after 5 minutes. The TV is also on when I do the
slideshow.

On the slideshow, when I start the slideshow, there is a Roku menu that
asks if I want to continue viewing slideshow. It then changes the picture
once, but that box is still there. It then will not change the picture.
After I click continue, it works as normal.

For the screensaver, when it comes on, it says
Screensaver paused in the corner, it will change pictures once, then it
will freeze on the second picture with the words screensaver paused in the
corner.

I've attached pictures, hope it helps.

**Comment by path0000** [comment]
I am having the same issue on a 55 inch TCL ROKU TV.   The screensaver charges pictures once,  then says it's paused.

**Comment by chtaylo2** [comment]
@bmorenico / @path0000 - Could you please add this pre-release version and see if it resolves the issue you're seeing?  - https://my.roku.com/add/QVH6NQ

When slide show is started in the app, what does the text say in the bottom left hand corner after "DEMO v3.3.1".

Thanks

**Comment by path0000** [comment]
That appears to have resolved my issue.   Screen says
DEMO v3.3.1: GetModelType() = TV

**Comment by bmorenico** [comment]
DEMO v3.3.1: GetModelType() = TV

Slideshow is working correctly

I tried the screensaver as well, it states the same demo language and is
also working correctly.

Looks like the next version will fix it. Thanks so much for the quick
responses and the whole app in general.

My 18 month old daughter is always screaming "show show" which is her way
of saying she wants to see pictures and videos of herself. Your app is
invaluable for my parenting.

**Comment by timrit** [comment]
I had the same problem. Downloaded v3.3.1 and now it works FYI.

**Comment by chtaylo2** [comment]
Bug fix has been submitted for publishing. Should be out in the next couple days
