### ISSUE TITLE
How to select specific album for screensaver?

### ISSUE THREAD

**Issue by phillyman2633** [chtaylo2/Roku-GooglePhotos#245]
I have a specific album set up in my Google Photos that has some promo pics in it (I specifically created for my Chromecast a few years ago). Downloaded this extension for Roku which is awesome but it randomly cycles through the entirety of my photos, which sucks because I have a lot of crappy cell phone pics that auto-sync with Google that I dont want to see on my TV. Is there a way to select a single album to display for the screensaver? I've been shuffling through the settings for 20 minutes and cant figure it out. Thanks!!!

**Comment by chtaylo2** [comment]
See: https://github.com/chtaylo2/Roku-GooglePhotos/issues/178
