### ISSUE TITLE
Screensaver paused

### ISSUE THREAD

**Issue by phillyman2633** [chtaylo2/Roku-GooglePhotos#249]
If the screensaver comes up, it cycles through my photos for about 5 minutes before it pauses the screensaver and stops cycling through photos (just displays the last picture before it paused, indefinitely). Is there a way to stop it from pausing on its own and just continuously cycle through pictures? I have an old-school plasma TV so if i forget to turn the TV off, burn-in is an issue. Thanks!

**Comment by chtaylo2** [comment]
@phillyman2633 - "Screensaver Paused" is what happens when a HDMI-CEC event is triggered. Meaning the TV was or is powered off at some point during the slideshow. Agreed the photo should disappear to prevent burn-in and will make that change.

When you see this "Screensaver Paused" message, was your TV powered off at any point? 

If not:
What Roku device are you using?
Are you seeing the same issue during normal slideshow playback inside the PhotoView App?

**Comment by phillyman2633** [comment]
Hello,

No, the TV is not powered off at any point during this occurrence. The TV
is on, it will basically cycle through photos for 10 minutes or so and then
pause ("Screensaver Paused" in the bottom left of the screen) and then it
will stay like that until we push a button on the Roku remote.  TV is a
Panasonic TC-P65VT60, Roku is Roku Ultra (4K).  The issue doesn't happen
during slideshow playback, only when the Roku screensaver is activated.

Thanks!

**Comment by skrevier** [comment]
I was having the "Screensaver Paused" issue.. When the screensaver came on it would say paused and show 2 photos and stop and stay on the 2nd one. When I saw the mention of HDMI - CEC here, on a hunch I disabled it in Settings and the Saver has returned to working as expected. So far..

**Comment by Eserim** [comment]
I'm having this issue now -even when going into settings and doing a "preview" it goes into being paused

**Comment by newsplexer** [comment]
Whenever the screensaver automatically kicks in, it comes up with a black screen and white text in the lower-left corner that says "Screensaver Paused." Of course, pressing the play button on the remote kicks one out of the screensaver entirely, so don't know how to unpause it. When going in though the app itself to activate slideshow mode, a photo comes up but with a dialog saying "! Slideshow Paused" and "Do you want to continue viewing slideshow?" with a "• Continue" button. Click to continue, and the slideshow progresses normally. But everytime you come back to the app, you have to first overcome this paused status. How to unpause in both environments? Am using a Roku Streaming Stick plugged into an HDMI port on a Samsung led TV.

**Comment by Eserim** [comment]
I found the only way to get over this was to remove the app, restart the Roku and reinstall - it happens to me every so often

**Comment by Eserim** [comment]
This is happening very often now - although a simple Roku restart usually sorts.

**Comment by chinarut** [comment]
ah - this thread was helpful.  When I turned off my Vizio, it paused the Screensaver and didn't resume when I turned the TV back on.  Disabling HDMI-CEC seems to allow the screensaver to just continue so when we turn our TV back on, it just shows wherever it's at.

I also a more desirable behavior is to leave HDMI-CEC enabled and for the screensaver to automatically unpause when the TV is turned back on?   Is a control event sent over when the TV is turned back on that the screensaver/Roku can catch?

**Comment by gregmo72** [comment]
I signed up to Github to comment on this.  Going into the channel works great but the screensaver doesn't work at all.  I immediately get this paused message.  This morning it had a messaged that I hadn't noticed before about expiring after 12 hours.  How does a screensaver expire?  This doesn't happen with any other screensaver I've used.

**Comment by chinarut** [comment]
how is this completed?

When I switch to my Roku, the screensaver still shows up black & timed out.
