### ISSUE TITLE
Google Photos Access Expired error

### ISSUE THREAD

**Issue by mikeethek** [chtaylo2/Roku-GooglePhotos#259]
After the PhotoView screen saver on my Roku has been running for about a half hour or less, this message comes up and I have to reregister. This is a pain! 
![20190825_125056](https://user-images.githubusercontent.com/54546163/63704289-9c929f80-c7df-11e9-80a4-e598de09a10e.jpg)

**Comment by chtaylo2** [comment]
Please see: https://github.com/chtaylo2/Roku-GooglePhotos/issues/189
