### ISSUE TITLE
Want to only play 1 album

### ISSUE THREAD

**Issue by OpenInference** [chtaylo2/Roku-GooglePhotos#261]
I have one album in my Google Photos.  The screen saver seems to play the album as well as almost any picture from my Google Drive account or Google Pictures.

I want the screen saver on my Roku to just play an album not anything from my pictures.

How do I do this and where is it finding the pictures?

**Comment by chtaylo2** [comment]
See details here: https://github.com/chtaylo2/Roku-GooglePhotos/issues/178
