### ISSUE TITLE
Feature Request - Date / Filename overlay option to screensaver

### ISSUE THREAD

**Issue by mmlmrx** [chtaylo2/Roku-GooglePhotos#262]
Hello, and first of all THANK YOU for this great app!  It is nearly perfect for what I wanted on my two Roku-enabled TV's.  

I noticed somewhere you mentioned that the caption will display on-screen.  Would it be possible to instead display the filename?  Here is my recommendation of how it could work

- [ ] Settings options:
- Display image caption
- Display image filename
- No text display
- [ ] Display as much of filename/caption as possible 
- It could just trail off with ... near the right side of the screen, or it could wrap to two(?) lines
- Not sure if you can do dynamic text size since TV could be 720/1080/4k
- [ ] Remove .jpg/.png/.gif/etc from the end of the filename
- [ ] Display text inside contrasting background color, so text is always readable

The only issue I see is how to avoid screen burn-in.  Is it possible to vary the vertical position of the text display with each image refresh, so that it never overlaps where it has just been?

EDIT: I just noticed that you are already changing the position of your banner, so I removed that reference to avoid confusion.  Thanks for thinking of that!!

Thanks again!

**Comment by chtaylo2** [comment]
@mmlmrx -- Want to make sure I understand what you are referring to. 

There currently is an overlay which displays multiple pieces of metadata on an image. The screensaver does not have any overlay but the in-app display does.

1. Creation date per Google
2. Filename per Google
3. File capture (if there is any)

**This image is an example showing the filename:**
![roku-screenshot-1573617893477](https://user-images.githubusercontent.com/16865602/68732562-df277500-05a1-11ea-984e-04b3c56c0575.jpg)

**This image is an example showing the caption & filename:**
![roku-screenshot-1573617885527](https://user-images.githubusercontent.com/16865602/68732564-e2bafc00-05a1-11ea-9c1b-e71e28f9b04d.jpg)

Are you looking for something different?

**Comment by mmlmrx** [comment]
Hi Chris,
   Thanks for replying.  Yes, that is what I am hoping to see - but on the screensaver.  I have this running on a TV and people keep asking me "what's that picture?", but I have thousands so I don't know each one.  

However, from a design perspective, I would not recommend using the same overlay you have in-app, as that dark bar obscures too much of the photo.   If you remove the bar, it would look perfect using that same text, as long as you had a contrasting color outline (not a highlight), so that it would be readable no matter the background color.  The only other suggestion I would have is to vary the vertical spacing slightly for each picture, so as to avoid potential screen burn-in.  

Thanks again!  I get a lot of compliments on my 65" digital picture frame...  :-)

**Comment by tmetzger** [comment]
I would also love to see captions on the screensaver!

**Comment by chtaylo2** [comment]
This has been completed in release 3.7. Will be released soon. Duplicate to #275

**Comment by mmlmrx** [comment]
Thank you @chtaylo2!  You should get a commission from Roku because this app is the reason I am buying another Roku stick for my LG CX (since they don't allow custom screensavers).  🥇
