### ISSUE TITLE
Bug: Slideshow Paused Glitch

### ISSUE THREAD

**Issue by OfficeGeek888** [chtaylo2/Roku-GooglePhotos#263]
This bug has been giving me headaches for a while now. More often than not, I would click on a photo and it would say, "Slideshow paused, would you like to unpause it?" or something like that, then it skips over to the next photo. This is irritating me because I can't browse through photos without this problem persisting.

**Comment by chtaylo2** [comment]
This has to do with Roku's HDMI CEC integration. I've seen with as well on multiple applications before. I would suggest rebooting your Roku device and see if the problems persist.
