### ISSUE TITLE
Disable Slideshow Timer question

### ISSUE THREAD

**Issue by OfficeGeek888** [chtaylo2/Roku-GooglePhotos#264]
I've been wanting this option for quite some time. I'm not content with having a slideshow timer because the slideshow must be manually paused. I'd love the option to disable the timer.

**Comment by chtaylo2** [comment]
@OfficeGeek888 - What timer are you are you trying to disable?

**Comment by OfficeGeek888** [comment]
> @OfficeGeek888 - What timer are you are you trying to disable?

The slideshow timer. Because the only options are 5 seconds, 10 seconds, 15 seconds, 30 seconds & custom, but no disabled option. It's kind of annoying because I have to set it to 999 seconds on custom.

**Comment by chtaylo2** [comment]
There's multiple ways to accomplish what you're looking for.

1. When a slide show starts, tap the OK button on remote. This will pause the slideshow and disable the rotation timer. Taping the LEFT and RIGHT directional arrows act in a similar way. Hitting the UP and DOWN direction arrows will turn on/off the overlay.

2. Creating an album with only 1 photo will cause the slideshow to start and hold on that single media item indefinitely.
