### ISSUE TITLE
Photoview does not display text and location maps that have been inserted in album

### ISSUE THREAD

**Issue by Rokjzf** [chtaylo2/Roku-GooglePhotos#267]
In my laptop version of Google Photos, I inserted text and location maps between photos. Although they display in my laptop version of the selected album, these additions dot not show when the selected album is displayed by the Photoview app on Roku.

**Comment by chtaylo2** [comment]
@Rokjzf  - Could you take some screenshots of what you're referring to and email me? rokuphotoview@gmail.com

**Comment by Rokjzf** [comment]
Chris, thanks for the quick response. Below are the two issues that I described. Thanks – John

The image below taken from my windows laptop shows the text image “Entering Rome” that I inserted below three photos using Google Photos. This image does not show when I review the album through the Roku device on my TV.




The image below shows three photos followed by a map  inserted using Google Photos. The map does not show when I review the album through the Roku device on my TV.





John and Diane Frazer    204-261-1809    johnzfrazer@gmail.com    NEW PERSONAL EMAIL ADDRESS

**Comment by chtaylo2** [comment]
Got it. So you'll need to add the text details to the photo description in Google Photos, directly. The text that you have inside the album is not something Google exposes via their API. We can only access the description in each photo

In Google Photos > Select Photo > [ i ] > Add Description

**Comment by Rokjzf** [comment]
Okay thanks. What I may do is create some jpgs with text in them. I presume I have the same issue with the maps?


John and Diane Frazer    204-261-1809    johnzfrazer@gmail.com    NEW PERSONAL EMAIL ADDRESS
