### ISSUE TITLE
Constantly having to re-register. Cannot use Photoview!

### ISSUE THREAD

**Issue by corzo99** [chtaylo2/Roku-GooglePhotos#268]
After the PhotoView screen saver on my Roku has been running for about a half hour or less, I have to re-register. The software is useless as is. What is causing this issue? 
![20191018_101436](https://user-images.githubusercontent.com/56706423/67222418-25921580-f3e2-11e9-8f80-8e811d5af45a.jpg)

**Comment by chtaylo2** [comment]
Please see: https://github.com/chtaylo2/Roku-GooglePhotos/issues/189

**Comment by corzo99** [comment]
Hi,

Thank you for the support.
I am unfortunately having the same issue. It randomly times out and expires
the token.
It happens if I turn off the TV for sure as well as while viewing.

I would appreciate a fix for this issue. Love the app but I cannot leave it
unattended.

Miguel
