### ISSUE TITLE
Bug: Items inherit page 1 names

### ISSUE THREAD

**Issue by OfficeGeek888** [chtaylo2/Roku-GooglePhotos#269]
This bug has been irritating me for a while now. Media pages are a new feature on this channel, but one qualm I have is when I go to pages besides page 1, the item names are the same as on page one.

As a consequence, I'm shooting in the dark to find a certain movie because the page 2 item [Movie2]  displays the same name as the one on the first page [Movie1]. So it's impossible to tell which one is which.

**Comment by chtaylo2** [comment]
Confirmed bug. Will address with next release

**Comment by chtaylo2** [comment]
Fixed. Will go into the next release.
