### ISSUE TITLE
Black screen with no photo as well as no thumb nail. 

### ISSUE THREAD

**Issue by smilinbev** [chtaylo2/Roku-GooglePhotos#271]
So...  was working great and then it wasn’t.  Lol.  I had a number of pics on an account that I display photos on tv and delete some and added others.  Has the name of the photo and 5he number of picture but black screen of death and no photo.  Uninstalled Roku app and reinstalled relinked 2 times and turn everything off and did it all again..  nothing worked help please have temp fix using different Roku app but I really like this one (photo viewer) that is..  would appreciate any help ideas from anyone.  Thank you in advance

Bev

**Comment by chtaylo2** [comment]
Google Photos itself was having issues yesterday. It’s working today
