### ISSUE TITLE
PhotoViewer support link and github.com 

### ISSUE THREAD

**Issue by NVF7777** [chtaylo2/Roku-GooglePhotos#272]
Re:  PhotoViewer for Google photos app.
Question1: Why does the PhotoViewer developer's website (www.photoviewapp.com)  "Support"  link send me to github.com   ?    
Question2: Can users send issues questions directly to the PhotoViewer developer?  If so, how?    Question3: Are the PhotoViewer issues posted to github.com directed to or read by the PhotoViewer developer?

**Comment by chtaylo2** [comment]
Yes, i'm the developer.
