### ISSUE TITLE
PhotoViewer for Google Photos -  Photo location/source

### ISSUE THREAD

**Issue by NVF7777** [chtaylo2/Roku-GooglePhotos#273]
I'm a  PhotoViewer for Google Photos user. I use ROKU to view Google Photos thru PhotoViewer.    I noticed that after I log off my Google account,  my Google photos remain viewable on PhotoViewer.   Question 1:  Why is this?   
Question 2:  How can I discontinue/stop PhotoViewer access to my Google Photo library ?

**Comment by chtaylo2** [comment]
When you grant the Roku application access, this is outside your current logged in web session. To unregister your account from the device:

Main screen > Settings (Gear Icon) > Unregister account from device. This will remove all tokens and account from the device.
