### ISSUE TITLE
Feature Request: Remove screensaver watermark

### ISSUE THREAD

**Issue by nobleburgundy** [chtaylo2/Roku-GooglePhotos#274]
I hear ya...
```
        'Show watermark on screensaver - Stop bitching, we need some advertisment!
        ds = m.device.GetDisplaySize()


        if ds.w = 1920 then
            m.Watermark.uri = "pkg:/images/PhotoViewWatermark_FHD.png"
        else
            m.Watermark.uri = "pkg:/images/PhotoViewWatermark_HD.png"
        end if
        m.Watermark.visible = true
```
, but most of the people using this feature went through setting up the PhotoApp and are just using it personally, so it's not really advertisement to users who already use the app. Isn't better to have more people using it? Guessing for many like me, it's a deal-breaker.

**Comment by goulav** [comment]
Yes. I’ll even pay for it!

**Comment by patrickwalton** [comment]
I would pay to remove the watermark too. It is a deal breaker for me.

**Comment by chodthewacko** [comment]
I greatly dislike the watermark and would pay to remove it.
It's not a dealbreaker as it's the only option on Roku, but it is enough to make me switch if I find an alternative.

And I don't get the 'we need the advertisement' part.   Do you think someone is going to use photoview in a public setting?   More likely, it's a personal user and the user will mention it's photoview.

**Comment by chris84wa** [comment]
Would love not have the watermark too and even pay for it for my business! There's nothing great on Roku otherwise. :/

**Comment by chtaylo2** [comment]
This is not an option being considered at this time.
