### ISSUE TITLE
Feature Request: Show filename as overlay

### ISSUE THREAD

**Issue by privington** [chtaylo2/Roku-GooglePhotos#275]
Was sure i saw an existing request for filename (#262) but don't see it now.
I have 10's of thousands of images in Google Photo's going back to 2004 and love randomly seeing images i haven't seen in years show up on my TV. 
Its great seeing my own photos.
Some are so good that i want to find them in my catalog/album and revisit it more directly which is almost impossible without a filename or the date it was taken (from EXIF)
With the filename showing (should be an on/off pref) i would be able to note it down, and then do a search for it in Google Photos, and download it to my computer, or better yet, search for it in my Master Photo catalog.
I did see that there is a Caption overlay feature, so the filename could be an alternative added to that existing feature. Hope it is an easy addition.

**Comment by chtaylo2** [comment]
@privington  - Want to make sure I understand what you are referring to. 

There currently is an overlay which displays multiple pieces of metadata on an image.

1. Creation date per Google
2. Filename per Google
3. File capture (if there is any)

**This image is an example showing the filename:**
![roku-screenshot-1573617893477](https://user-images.githubusercontent.com/16865602/68732345-1ba6a100-05a1-11ea-8b08-ca7e285aaa64.jpg)

**This image is an example showing the caption & filename:**
![roku-screenshot-1573617885527](https://user-images.githubusercontent.com/16865602/68732399-3d078d00-05a1-11ea-9491-5f465e1071a4.jpg)

Are you looking for something different?

**Comment by privington** [comment]
Sorry for the delay.
Looking for that same overlay feature but in the SlideShow mode.
When the SlideShow is running I'm seeing images of mine I haven't seen in years and I want to go find them in my master photo catalog.
If I set the picture view time to 15 sec or so that is long enough for me to note down the image name, since I am usually seeing the image out of the corner of my eye while doing other things.
It would be better if the date was shortened to 2019-12-02 and the type was just outlined with white and a black keyline around that.
Sort of Caption like when watching foreign language films. Discrete yet visible.
So glad the register issue got sorted. Has been working great. 
Not sure how the image selection works though. I always see current images coupled with a specific album of older images character back and forth. Would like to know if that is controlable.
Cheers
Peter Rivington

**Comment by jimmydfl** [comment]
Would like to see the metadata as an option to turn it off. Thanks

**Comment by privington** [comment]
Yes, the filename and date would be the most useful info for finding the image in my 300K plus collection of photos. Being into photography, other camera and settings metadata would also be of interest as well but only if a checklist of what could be seen on screen was available to turn on or off.
The filename on its own would work but with filename creation cycling after 1000 images typically, over decades many photos and up with the same name. Not so many that it can't be found, so not a big hindrance.
Thank you for your consideration of this request. Sorry my responses are so delayed. 
Does your reply get sent as an email?
If yes then I am obviously not seeing them.

**Comment by alexei2001** [comment]
Yes, thank you for this project. I also would like to have a configurable option to show Metadata in the slideshow mode.
Keep up the great work!

**Comment by chtaylo2** [comment]
This has been completed in release 3.7. Will be released soon.
