### ISSUE TITLE
Development setup / stuck on auth token

### ISSUE THREAD

**Issue by mmaday** [chtaylo2/Roku-GooglePhotos#279]
Hello and happy holidays!

I was hoping to explore a few enhancements, but have hit a roadblock setting up my development environment.  After following the instructions at `private.brs` (and copying it to `private-git.brs`), I get the following when running the app:

![photoview-error-dev](https://user-images.githubusercontent.com/1237074/69832303-57b54500-11e2-11ea-9dcf-8de5daf44b2e.jpg)

The Roku console messages show:

```
Registration.brs [doGenerateToken]
Common.brs [makeRequest]
--------------------------------------------------------------------------
Received event type 'roSGNodeEvent'
UrlHandler.brs - [addRequest]
Initiating transfer '122687384' for URI 'https://www.photoviewapp.com/cgi-bin/device/code' succeeded: true
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Received event type 'roUrlEvent'
UrlHandler.brs - [processResponse]
Response for transfer '122687384' for URI 'https://www.photoviewapp.com/cgi-bin/device/code'
Registration.brs [onNewToken]
Registration.brs [onNewToken]
--------------------------------------------------------------------------
```

I assume this is due to a disconnect between my Google OAuth key and your auth layer at https://www.photoviewapp.com/cgi-bin/device/code?  Or is the issue that I do not have the Google API scopes set correctly?  Adding Google Photos (read-only scope `https://www.googleapis.com/auth/photoslibrary.readonly`) looks like it requires submission and approval.  Here's my current scope:

![roku-oauth](https://user-images.githubusercontent.com/1237074/69832458-4c164e00-11e3-11ea-99b6-bc55b7368aa0.png)

Do you have any thoughts here?  Any additional insight is appreciated.

Thanks!

**Comment by chtaylo2** [comment]
@mmaday - Thanks for your interest. Unfortunately Google took their hosted authentication screen away so had to build me own. Shoot me an email with some ideas you're looking at and we can review adding you to the development account.   Email: rokuphotoview@gmail.com

Thanks

**Comment by alexkev** [comment]
@chtaylo2 I ran into the same issue. I would like to help with this project, is there any way i can be added to the development account or did you find a work around?

**Comment by chtaylo2** [comment]
@alexkev - Hi Alex, shoot me an email at rokuphotoview@gmail.com and we’ll get you setup.

thanks
