### ISSUE TITLE
Feature Request: Display Location via Reverse Geocoding (automated conversion of Latitude Longitude Data)

### ISSUE THREAD

**Issue by kdaly132** [chtaylo2/Roku-GooglePhotos#281]
Chris, Would love to have PhotoView help me remember where I took my pictures. Came across your response on photo data below. I'm no programmer but does appear there are some tools for converting latitude / longitude data into human readable addresses (City, State)

Here's a link I started going through but its beyond me:

https://developers.google.com/maps/documentation/geocoding/start 

Would this be possible to add to the screensaver for photos that have this data stored? Thank you!!

___

Scope for this feature request will be the addition of the photo description added to the overlay. If additional Info is added in the Google Photo application, it will start to be displayed on the overlay.

Geodata is sent back, but only longitude and latitude. Not sure at this time how we would translate that to an actual location.

_Originally posted by @chtaylo2 in https://github.com/chtaylo2/Roku-GooglePhotos/issues/117#issuecomment-404031345_

**Comment by chtaylo2** [comment]
Thanks for the details.  We'll keep this in backlog and will look into it.

**Comment by chtaylo2** [comment]
Unfortunately in the current Google API, they are not returning the location data which are attached to images.

As of current, here is all we can get:

`      "mediaMetadata": {
        "creationTime": "2020-12-06T16:43:40Z",
        "width": "3024",
        "height": "4032",
        "photo": {
          "cameraMake": "Apple",
          "cameraModel": "iPhone 11",
          "focalLength": 4.25,
          "apertureFNumber": 1.8,
          "isoEquivalent": 200
        }
      },
      "filename": "IMG_4134.jpg"
    },`

Closing this at this point
