### ISSUE TITLE
Timeout after 12 hours

### ISSUE THREAD

**Issue by grimblefritz** [chtaylo2/Roku-GooglePhotos#283]
I want to run a slideshow from about 4-6pm until around 8-10am the next day. The exact duration varis.

I start the show and all is well. However, the next day I find a blank screen with a message that the app (screensaver) timed out after 12 hours.

Is there a way to fix this so it will run indefinitely?

**Comment by chtaylo2** [comment]
@grimblefritz - Google Photos gives us an application limit on the number of photos that can be pulled in a 24-hour period. This limit is placed to reduce people running a screensaver for many hours and no one viewing it. If you are inside the application, it'll run for 24-hours before expiring but the screensaver is 12-hours.

No plans to change this at this time.
