### ISSUE TITLE
Slide duration of 3 seconds

### ISSUE THREAD

**Issue by grimblefritz** [chtaylo2/Roku-GooglePhotos#284]
I want to use the app to display small (1-5 word) messages. In very large text so it is readable from 100-200 feet away. As such, the current minimum delay of 5 seconds feels like forever.

Would it be possible to add an option for a 3 second delay? Or even 1.5 and 3 seconds?

**Comment by chtaylo2** [comment]
Sorry, but 5 seconds is the minimum at this time. It helps control the quota that Google Photos gives to this application.
