### ISSUE TITLE
Only shows a subset of album photos?

### ISSUE THREAD

**Issue by jgodfrey** [chtaylo2/Roku-GooglePhotos#285]
I've connected PhotoView to 2 Google albums. In total, the albums contain approx 615 photos. When the slideshow is running (just as the default Roku screen saver, with Random photo selection), I seem to see only a fairly small subset of the album images. Additionally, I see some of the same images repetitively and certain images show up unusually often. 

Is there a limit to the number of photos PhotoView can/will work with? With 600+ images, it's difficult to tell *exactly* what's going on, but it feels like it's working with a much smaller image set than I expect...

**Comment by chtaylo2** [comment]
@jgodfrey - The screensaver will pull 5 albums randomly, unless you've selected specific. Within each of those albums, it'll make a max of 12 API calls which typically gives 80-100 items each = ~1000/items. With that said, Google Photos API is very obscure about how they select the items to return and sometimes its less then this. 615 items shouldn't be a problem. 

I would suggest seeing how many items are returned inside the PhotoView channel and see if it equals the album size. This is the same query the screensaver uses.
