### ISSUE TITLE
Feature Request: Mix Photo & Video in slideshow

### ISSUE THREAD

**Issue by cjust1** [chtaylo2/Roku-GooglePhotos#286]
I have albums that have both photos and videos in them.  It doesn't appear that I can start a slideshow with both.  Would that be a possibility.

**Comment by chtaylo2** [comment]
Thanks for the suggestion. This has been requested before and is currently in backlog. See: https://github.com/chtaylo2/Roku-GooglePhotos/issues/139 

No plan yet on when this will be added in as it's a pretty significant change.
