### ISSUE TITLE
Ideas on Screensaver within Channels

### ISSUE THREAD

**Issue by Marvelguy** [chtaylo2/Roku-GooglePhotos#288]
When the screensaver takes over while we are within a channel, it starts the Roku name screensaver even though I have chosen the PhotoView screensaver.  When I am on the menu screen, it starts the PhotoView screensaver like it is supposed to do.  Any ideas?

**Comment by chtaylo2** [comment]
@Marvelguy -- I tested this and was not able to reproduce. Can you set your screensaver to 1 min, take a video and send to me showing this?  Email: rokuphotoview@gmail.com

**Comment by Marvelguy** [comment]
Ok, here is a link to the video I made showing the issue.

https://photos.app.goo.gl/jCC7bABCKDgweajQA

Thanks!

Sam
