### ISSUE TITLE
Enhancement to turn photos 90 degrees

### ISSUE THREAD

**Issue by catfanscott** [chtaylo2/Roku-GooglePhotos#29]
While viewing photos, there isn't a way to turn photos that are sideways.  Half turn left, half turn right.  Would be nice to view our pics correctly,  when most pictures were taken by tablets and phones. A button for turning pic 90 degrees would be wonderful on the roku 4k ultra model.

**Comment by chtaylo2** [comment]
catfanscott,  While I don't anticipate the Google Photos ROKU app doing this (mainly because of API limitations with Google) you are able to easily rotate photos in Google Photos. 

- https://photos.google.com/
- Select Photo > Edit 
- Then click the rotate button until the photo is correctly aligned. 

I tried this tonight and after rotating, the Google Photos ROKU app currently showed the new rotation. 

Hope this helps.

**Comment by catfanscott** [comment]
That'll take quite awhile with over 9000 photos


Sent from my Galaxy Tab A
-------- Original message --------From: Chris Taylor <notifications@github.com> Date: 1/23/17  10:07 PM  (GMT-06:00) To: chtaylo2/Roku-GooglePhotos <Roku-GooglePhotos@noreply.github.com> Cc: catfanscott <catfan@ymail.com>, Author <author@noreply.github.com> Subject: Re: [chtaylo2/Roku-GooglePhotos] Enhancement to turn photos 90
  degrees (#29) 
catfanscott,  While I don't anticipate the Google Photos ROKU app doing this (mainly because of API limitations with Google) you are able to easily rotate photos in Google Photos.

https://photos.google.com/
Select Photo > Edit
Then click the rotate button until the photo is correctly aligned.

I tried this tonight and after rotating, the Google Photos ROKU app currently showed the new rotation.
Hope this helps.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/chtaylo2/Roku-GooglePhotos","title":"chtaylo2/Roku-GooglePhotos","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/chtaylo2/Roku-GooglePhotos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chtaylo2 in #29: catfanscott,  While I don't anticipate the Google Photos ROKU app doing this (mainly because of API limitations with Google) you are able to easily rotate photos in Google Photos. \r\n\r\n- https://photos.google.com/\r\n- Select Photo \u003e Edit \r\n- Then click the rotate button until the photo is correctly aligned. \r\n\r\nI tried this tonight and after rotating, the Google Photos ROKU app currently showed the new rotation. \r\n\r\nHope this helps. "}],"action":{"name":"View Issue","url":"https://github.com/chtaylo2/Roku-GooglePhotos/issues/29#issuecomment-274704707"}}}

**Comment by chtaylo2** [comment]
This should be fixed with v2.0 of the channel.
