### ISSUE TITLE
Feature Request: Display current time

### ISSUE THREAD

**Issue by pyurkin** [chtaylo2/Roku-GooglePhotos#298]
Hello!
I used google chromecast screensaver as photo viewer and there was current time on bottom right corner. I found this very convenient. Could you add such feature in Roku-GooglePhotos screensaver?

**Comment by chtaylo2** [comment]
I like this feature request. Will keep it in the feature request for action.

**Comment by chtaylo2** [comment]
In progress

**Comment by chtaylo2** [comment]
Completed - Needs functional test during UAT. Moving to resolved.  Feature will be released as part of v3.5
