### ISSUE TITLE
New user: my settings are not saving

### ISSUE THREAD

**Issue by toejam1** [chtaylo2/Roku-GooglePhotos#299]
I just setup Photo View on my Roku Ultra and went through the settings.  I changed delay from 8 seconds to 5 seconds, viewed the photos, went back to settings and they're back to 8 seconds.  Am I missing something?

**Comment by chtaylo2** [comment]
There are two settings which can be set, Global and Session (Temporary).

- Global settings (Main Menu > Settings) will persist across channel exits.
- Temporary settings (Slide Show Display > * Button > Settings) are only temporary for that session. They will disappear next time you load the channel.
