### ISSUE TITLE
Cache UHD photos so there isn't a switching delay

### ISSUE THREAD

**Issue by patrickwalton** [chtaylo2/Roku-GooglePhotos#302]
The TV is hanging between photos and I assume it's because I turned the UHD setting on. Is there a way they could get downloaded on setup so they don't delay when the screensaver is running?

**Comment by chtaylo2** [comment]
Regardless of the resolution you select, it will pre-cache up to 5 images during the initial load. This happens in general slideshows and the screensaver. If UHD is lagging for you, it can't even keep up with pre-caching, so highly recommend reducing your res to FHD. UHD takes alot of bandwidth, most photos will be 5-6 MB min.


Code snippet: https://github.com/chtaylo2/Roku-GooglePhotos/blob/master/components/Slideshow/DisplayPhotos/DisplayPhotos.brs#L381-L411
