### ISSUE TITLE
Captions not showing in slideshow

### ISSUE THREAD

**Issue by rsass3** [chtaylo2/Roku-GooglePhotos#305]
How do I display photo/video captions when using slideshow mode. The caption display when using browse mode but not slideshow mode.
Thanx

**Comment by chtaylo2** [comment]
When you say "captions" are you referring to the photo details / date? a.k.a Pause overlay.

The "Pause Overlay" is displayed when you Pause a slide show or Click UP / Down arrows during slide show.
