### ISSUE TITLE
App is displaying every photo in google library not just albums?

### ISSUE THREAD

**Issue by senorblues** [chtaylo2/Roku-GooglePhotos#308]
Photo view seems to be showing every photo in google photos not just the albums that the app gives the appearance it will display due to the user interface. It sure seems like people would only want to show specific albums or at the most all google user named albums not the complete google library (is ‘google library album’) on their configured screensaver. Uninstalling, as this is a security risk to me and I’m sure to others.

**Comment by chtaylo2** [comment]
You can display whatever album or photos you wish. If you want to select only a single album or multiple: See here: https://github.com/chtaylo2/Roku-GooglePhotos/issues/178
