### ISSUE TITLE
Display 1 picture, avoid timeout to main TV screen

### ISSUE THREAD

**Issue by wmutschler** [chtaylo2/Roku-GooglePhotos#309]
Hi,

I have a simolar issue that was posted in #260 but i did not see a solution.  I am trying to permantly display a single image w/o ever going to a screensaver rotating to other images.  I have disabled the screensaver though roku.  However, after about 1 1/2 hours, the photview app closes and TV returns to main home roku screen. I have talked to the TV manufacturer (it is a roku TV) and they claim this is not a funtion of tv software programming.  Is there a way to prevent the app from reverting back to tv home screen?

Thanks,
Bill

**Comment by chtaylo2** [comment]
@wmutschler - When a single image is displayed it basically pauses all timers and sits there if nothing more to rotate. Assuming your screensaver is OFF, the channel it at the mercy of the Roku OS to keep the image displayed. It's possible after 1 1/2 hours, the Roku OS is crashing or going into some sleep mode.  In any case, it would be outside the scope of the channel.
