### ISSUE TITLE
In App Screen Saver

### ISSUE THREAD

**Issue by unclenibs** [chtaylo2/Roku-GooglePhotos#310]
When many apps like YouTube are open the screen saver reverts back to Roku default screen saver instead of photo view. Is there a way to fix this?

**Comment by chtaylo2** [comment]
Some apps have their own screensaver or have defaulted to use the Roku built in screensaver. Just make sure you have the PhotoView screensaver selected and thats all you'll be able to set.  If a channel has something else custom (ie.: YouTube / NetFlix) you won't be able to override those.
