### ISSUE TITLE
Allow album selection from screensaver mode

### ISSUE THREAD

**Issue by david-mcmahon** [chtaylo2/Roku-GooglePhotos#311]
Sorry if I missed where to do this, but it appears that when setting screensaver to google photoviewapp, there's no way to specify which albums are getting displayed.  It just cycles through all photos (or all albums?).  Most pictures I take I'm not interested in looking at on a slideshow.

**Comment by mazzarriol** [comment]
I'm experiencing the same.

@chtaylo2 Any updates on feature to fix it? Thanks!

**Comment by cbandy** [comment]
I feel like it used to be easier to get to the setting. This is how: https://github.com/chtaylo2/Roku-GooglePhotos/issues/178#issuecomment-609085594
