### ISSUE TITLE
Stop Sharing

### ISSUE THREAD

**Issue by dpearce8864** [chtaylo2/Roku-GooglePhotos#315]
I recently shared my google photos with my in-laws roku television and forgot to stop sharing when we left. Is there a way to turn off sharing from my end? Or do I have to have them do it from their television?

**Comment by chtaylo2** [comment]
@dpearce8864 - Yes you can.

1.) Go here: https://myaccount.google.com/security-checkup/3
2.) Expand "Show Others" under Third-Party Apps. 
3.) Revoke the PhotoView application.

This will remove access to any devices you've authorized. You can then proceed to reauthorize whichever device you'd like.
