### ISSUE TITLE
Screen goes blank after short period of play (~2 hrs?) , used to play for 12 hrs

### ISSUE THREAD

**Issue by DrStevensGoPh** [chtaylo2/Roku-GooglePhotos#320]
Within the last two weeks or so the PhotoView slideshow that I start each morning stops playing (I'm not sure of how long before it quits probably about 2  hrs.) and displays only a blank screen.  The ROKU TV set has not gone to sleep, etc. Pressing the Roku Home button allows me to restart the PhotoView App.  It had previously run every day without issue, stopping the slideshow only after 12 hrs. of play.  Has anything changed?  Is there more information I can provide to help troubleshoot?

**Comment by chtaylo2** [comment]
This was reported here:  https://github.com/chtaylo2/Roku-GooglePhotos/issues/319

There’s a proposed fix already posted. Give that a try and let me know if it fixes the issue

**Comment by DrStevensGoPh** [comment]
Thanks. I've downloaded the bug-fix version and have started testing.  I'll let you know my observations.  Thanks!

**Comment by DrStevensGoPh** [comment]
Hi Chris -

The problem described in #319 is a little different than my issue.  The app
works perfectly for about 2 hours, then the Roku TV displays a blank
screen, bu the TV is still on. I have tested the Bug-Fix version (build
ending in *0265) multiple times today and the problem persists. The
slideshow runs for approximately (maybe exactly) 2 hours and then a blank
screen is displayed (non necessarily a blank slide/photograph).  I
believe the app quits running after about 2 hrs.  When I press the
Home button on the Roku remote I have to re-launch the app.  I'll continue
observing for patterns, etc.  If there is any other info you need or tests
you'd like me to perform, please let me know.

~~ Dave

**Comment by chtaylo2** [comment]
Does this happen in both the screensaver and when displaying a slideshow inside teh app?
If inside the add, when the display does blank and showing slideshow in progress, can you press the OK, left, right direction arrows, and does anything happen?

Have you tried disabling your screensaver and does it continue to do the same thing?  Does it do this if idle in another Roku Channel? I've never seen this before.

**Comment by DrStevensGoPh** [comment]
Hi Chris -

I use this ROKU TV exclusively for displaying photos, so all my
observations are based on using the PhotoView app (vs idle Roku screen
saver.)

My remarks pertain to the "3.5.1 DEBUG" version referenced as a fix for
problem #319:

The failure occurs for me almost exactly after 2 hours of play, it appears
that the app is, in fact, failing to fetch a photo.  Pressing the right
arrow after the failure displays the message "DEBUG ([ERROR] 400 seen with
'400')" and also displays the image name that should have been displayed
(e.g. "IMG_8438.JPG") and "## of 359"  where ## has been 99, 92, 83 and
likely others.

I've been experimenting and observing behavior the last few days, and this
is what I have discovered.
1.  I can observe the same problem on a different ROKU TV.
2.  If I change all settings back to default the app will run without
failing.
3.  The global settings I use are: Display duration = 90 seconds,
Resolution = High Definition 1080 and photo selection = random (Sorry, I
may not be using your exact terminology for these settings.) I've been able
to get both of my ROKU TVs to fail after 2 hrs using these settings.
4.  I have also observed failure at about 2 hours  when using other
non-default settings (e.g. display duration = 30 seconds.)

Hopefully this helps.  Again, I'm happy to perform any tests that may be
helpful in diagnosing and correcting the problem.

Thanks for your attention to this problem.  (I love the app!!)

~~ Dave

**Comment by chtaylo2** [comment]
Thanks.  I'll test with these setting and see if i can duplicate.  The fix to the other issue was released today.

**Comment by DrStevensGoPh** [comment]
Since my last message where I said it will run with default setting without
failing.  In subsequent tests, that is, in fact, not the case...sometimes
it will run the full 12 hrs, and sometimes it will fail within a few
hours.

An additional observation:  After a failure, if I press the remote's
BACK button the two PhotoView screens do not display the normal content.
It's as if they've somehow lost awareness of Google Photo content.  I've
attached photos of the "normal" condition and then what the screens looks
like after a failure.

Let me know if you need more info or if I can assist in any way.

~~ Dave

**Comment by chtaylo2** [comment]
Can you email them to me? Images do not come through on the GitHub comments. 
Email: rokuphotoview@gmail.com

Thanks

**Comment by itzme1234** [comment]
I just posted the same problem (I think) the app is working fine, but when set as screensaver just displays a black screen with an error message about being paused or expired.
