### ISSUE TITLE
Default Album

### ISSUE THREAD

**Issue by emhmpls** [chtaylo2/Roku-GooglePhotos#324]
I want to only have one of my Google photo albums display as a screensaver on Roku. Can I designate a specific album? If not, this would be a major improvement suggestion.

**Comment by kevinbeason** [comment]
One way to achieve this might be to create a new google account, share the desired Default Album to that account, and use that new google account (which only has a single shared album) for PhotoView.

**Comment by chtaylo2** [comment]
You can already do this. In the Customize Screensaver settings, select linked account and hit Right Arrow for the list of albums to show during screensaver playback.

**Comment by emhmpls** [comment]
Are you finding this option in the Roku screensaver are? I only see:

Change Screensaver Settings
Then nothing to choose a particular album

Thanks
Eric

Eric M Herr-Madsen
________________________________

**Comment by emhmpls** [comment]
Never mind. I found it. Thanks so much

Eric M Herr-Madsen
________________________________

**Comment by chtaylo2** [comment]
Reference: https://www.photoviewapp.com/faq/#screensaver-album
