### ISSUE TITLE
Limit access?

### ISSUE THREAD

**Issue by cjc1023** [chtaylo2/Roku-GooglePhotos#327]
Hello. I downloaded this channel onto multiple family members’ TVs so they can view shared albums if trips, kids’ sporting events, etc, however I’d rather them not have access to my entire Google Photos library. Is there a way to restrict access such that they can only view the shared albums?

**Comment by chtaylo2** [comment]
There's no way to limit access directly in the app. The recommended approach is to share 1 or more albums with your family members and they can then access the shared album directly inside the PhotoView app. This would only allow them access to this media and nothing else in your account.

**Comment by cjc1023** [comment]
Ah, I should’ve mentioned this wrinkle: I am signed in as myself. My parents don’t have a Google Photos acct, so my only option was to sync the app with mine. Sounds like I can only either do that and they’ll have access to everything or get them an acct and share the albums I want. Thanks for the response.
