### ISSUE TITLE
Feature Request: Allow favorites as an album

### ISSUE THREAD

**Issue by cpankonien** [chtaylo2/Roku-GooglePhotos#333]
please include the ability to select "favorites" as an album.

**Comment by chtaylo2** [comment]
I've looked at this in the past and at the time Google API did not have this ability to pull albums marked as favorites. I'll review again, but their API is far limited to what photos.google.com allows.

**Comment by chtaylo2** [comment]
This has recently been enabled in the GooglePhotos API. The plan will be to create a new entry under "DynamicAlbum" section with the option to view photos marked as Favorites.

Filter needed:
`{
  "filters": {
    "featureFilter": {
      "includedFeatures": [
        "FAVORITES"
      ]
    }
  }
}`

**Comment by cpankonien** [comment]
has this been released? I am unable to find it in dynamic albums.

**Comment by chtaylo2** [comment]
Not yet, due to https://github.com/chtaylo2/Roku-GooglePhotos/issues/364 had to pull back release to add this in. Still doing code testing.

**Comment by cpankonien** [comment]
ok thanks.

**Comment by chtaylo2** [comment]
@cpankonien  - Here's a candidate release if you'd like to try it: https://my.roku.com/account/add/MLTNH6
Should be published in the Channel store soon.
