### ISSUE TITLE
How to search?

### ISSUE THREAD

**Issue by louloizides** [chtaylo2/Roku-GooglePhotos#339]
I probably have close to 100k photos in my Google Photos account. I can't find a way to search through them by keyword, date, etc. Is there one? And if not, then I would really like to add this as a feature request.

**Comment by chtaylo2** [comment]
The channel used to have this feature but with the move to GooglePhotos new API, they dropped support for it.  You can see details here: https://issuetracker.google.com/issues/110300471.  Still an open feature request but unable to provide today.
