### ISSUE TITLE
Random photos not in album chosen

### ISSUE THREAD

**Issue by Jmead12000** [chtaylo2/Roku-GooglePhotos#340]
I have uninstalled and reinstalled 3 times. Seems to work for a while and then photos are appearing that are not in the album I have chosen. Photos that I don't want projected onto my TV. Help.

**Comment by chtaylo2** [comment]
Is this during the screensaver playback? You can select the albums(s) to show in Screensaver Settings > User selection. Make sure you have at least 1 selection made or it'll randomly choose albums to display.
