### ISSUE TITLE
Missing Google albums on Roku

### ISSUE THREAD

**Issue by acaltex** [chtaylo2/Roku-GooglePhotos#341]
Not all Google albums are being displayed and playing on Roku Photoview app, they always did before but now they are not being displayed

**Comment by chtaylo2** [comment]
The only albums which are excluded from display are ones marked as "Hangout" or "Private".  See: https://github.com/chtaylo2/Roku-GooglePhotos/blob/master/components/Slideshow/SlideshowHelper.brs#L175-L176

Other then this, the channel will return any which Google has provided in the API.  Does the above apply here? If they are Shared albums, they will be displayed on another screen, FYI.
