### ISSUE TITLE
Feature Request: Allow favorites as an album - FAQ needed

### ISSUE THREAD

**Issue by chtaylo2** [chtaylo2/Roku-GooglePhotos#344]
As part of #333 & #343, need to create an FAW to show folks how to mark items as a favorite to include in the dynamic album.

**Comment by alexkev** [comment]
@chtaylor2 Are you working on this feature now? I would like to help. I love this app and use it all the time and really want this feature implemented. How can I help?

**Comment by chtaylo2** [comment]
@alexkev - thanks for the interest. I updated the other issue so you can get development access.

Regarding this feature, the code is completed and I opened this to create an FAQ. Finishing upthe code to allow this new selection in the screensaver. Hope to have it released this month.

**Comment by chtaylo2** [comment]
FAQ created. https://www.photoviewapp.com/faq/#favorites
