### ISSUE TITLE
Security - Can I Limit PhotoView App Access to just one Google Photos folder

### ISSUE THREAD

**Issue by gerrete** [chtaylo2/Roku-GooglePhotos#354]
I used the app and was able to display the contents of a shared folder on my TV and loved it. Is there a way to limit the app's access to just specific folders that I choose. It looks like I am giving you permission to access all of my photos and I am not comfortable with that - not because I do not trust you as much as I fear that a breach would give someone else access to all of my photos rather than just the folder that I have chosen to share. I would much prefer to limit that control from Google's end. Any suggestions on how to accomplish this?

**Comment by chtaylo2** [comment]
@gerrete - I can respect the security mindset as a CISSP myself. I would recommend reviewing out privacy policy linked on the website: https://www.photoviewapp.com/privacy-policy/. This will detail out questions on data and access to accounts. Or I could say, non-access to access. Once you link your Roku device, no database or system retains access to your Google Photos access outside your local Roku.

With that said, if you are still concerned, you can always create a second Google Photos account and share the album(s) to this second account. Shared albums can be displayed just the same.
