### ISSUE TITLE
Question about timeout

### ISSUE THREAD

**Issue by dangoodtech** [chtaylo2/Roku-GooglePhotos#356]
I am looking into using this for our retail stores as a solution to show digital signage with photo slides.  The app is awesome and it looks like it will be perfect.  The only question I have is once the screensaver is on for 12 hours and times out how do you restart the screensaver?  Is it as simple as using the remote to "wake" up the Roku and then the screensaver will start up again (after the wait time)?

**Comment by chtaylo2** [comment]
@dangoodtech - Using the remote you can wake up the Roku and it'll then start back after your screensaver wait-time. This can be set as low as 1 minute.  

In an upcoming release the timeout will be turned off if looping through 20 or less images. So, that might be of interest. See more details here: https://github.com/chtaylo2/Roku-GooglePhotos/issues/358

**Comment by ghalevy** [comment]
> @dangoodtech - Using the remote you can wake up the Roku and it'll then start back after your screensaver wait-time. This can be set as low as 1 minute.
> 
> In an upcoming release the timeout will be turned off if looping through 20 or less images. So, that might be of interest. See more details here: #358. This release should be out in the next week or two.

@chtaylo2 Is it possible to set the timeout manually?  Or better yet, to disable the timeout altogether?  I am using this as a photo frame and it is awesome except for the timeout.

**Comment by chinarut** [comment]
@ghalevy my understanding is it can only be "disabled" if you limit to 20 photos with the new feature.

here's the reason the timeout exists: https://www.photoviewapp.com/faq/#timeout
