### ISSUE TITLE
Have to connect every time.

### ISSUE THREAD

**Issue by Undead420Stoner** [chtaylo2/Roku-GooglePhotos#37]
When I leave the app and goto something else on my roku, I come back to it and it says I need to link my account again at google.com/device. So I do it. Says missing information, I hit back and it let's me view my photos. But this happens every time.

**Comment by chtaylo2** [comment]
This is a known bug affecting some people. There is a new version currently awaiting publishing approval with Roku. You can install this as a work around until v1.6 is published.  https://my.roku.com/add/ZPTH2L

If you wouldn't mind, please update if this solves your issue.

Thanks

**Comment by chtaylo2** [comment]
No feedback..assuming resolved..
