### ISSUE TITLE
Some videos play and others don't

### ISSUE THREAD

**Issue by tktoddgithub** [chtaylo2/Roku-GooglePhotos#373]
Of my videos in Google photos, some play fine with Photoview and others do not open.  They are all .mp4 files either from a Samsung smart phone, a DJI drone or Adobe Photoshop elements.  They play fine on PCs, tablets and phones.  Was wondering if there is a characteristic to look for that might indicate why some play and others don't.  Thanks.

**Comment by chtaylo2** [comment]
Unfortunately this is a limitation of Roku and Google API. The video playing is not supported by Google API however we use a known workaround to play/stream the videos. It doesn't work for all videos. From my experience, if recorded from a mobile device, they seems to play fine, other sources may vary depending on the encoding.
