### ISSUE TITLE
BUG - Recent update has broken the back button on in app slideshow.

### ISSUE THREAD

**Issue by chtaylo2** [chtaylo2/Roku-GooglePhotos#374]
Pushing emergency bug fix to v3.7.1

**Comment by chtaylo2** [comment]
Pushing this popup for uses who have updated:

_We're aware of a bug this update has introduced. After starting a slideshow, the 'back' button does not work. Thats not good!
A fix has been submitted and Roku will release on Thursday, Feb 18th._

**Comment by tylerlatessa2001-png** [comment]
I have to get my car

**Comment by tylerlatessa2001-png** [comment]
Go to Walmart
