### ISSUE TITLE
Photo View App return Roku home screen after two hours

### ISSUE THREAD

**Issue by nathanb065** [chtaylo2/Roku-GooglePhotos#375]
Insignia Roku Build: 4200-20 v9.4.0 updated December 2020
TCL Roku Build: 4207-93 v9.4.0 Updated February 2021
Photo View Build: 5.616.20210216 v3.7.1

Hey Chris, 

I work in a museum where we use Roku TVs to display maps and information around our building. Currently, we have 5 Insignia TVs and 1 TCL TV. Over the last 2 weeks we've noticed an ongoing issue where the Photo View app will close on all displays after 2 hours of use.  Each TV has a Google image folder with 10 or less dedicated images at any given time.

I have been troubleshooting all TVs in an attempt to isolate the issue:
- Turn the TVs off and back on
- Completely restart the TVs and remove power for a few minutes
- Check for new updates
- Check and change TV settings
-      Sleep settings are off
-      Screen Saver is off
-      Power Saving is off
-      Bandwidth saver is off
- Check for Photo View updates
- Used other apps both on and off our internal network

Right now, we have 4 of 6 TVs disconnected from the network running the images through Roku Media Player.  
The TCL TV is still using Photo View on the network and exiting after two hours.  
One Insignia TV is running Roku Media Player via USB while connected to the network (the idea behind this is if Media Player closes too, it would be a Roku issue). 

The only thing I haven't tried was hard resetting the TV and entering our credentials again.  We definitely prefer using Photo View and have had minimal/no issues at all.  It's made our life easier and we really do like it.  If this is a bug, hopefully this helps bring attention to it.  If there is anything else I should try, I'm more than happy to give it a shot.  Thanks for all your time with this app.

**Comment by wmaclellan** [comment]
We've started experiencing a similar issue in the past two weeks using the Photo View App on 8 Hisense TVs.
Our slideshows are short 2-15 images. 
In the past we have slideshows ran the full 11 hours that we are open. Within the past two weeks the slideshows timeout to the Google Photo Albums screen at almost exactly the 2 hour mark. This is consistent with all 8 TVs.

I have copied nathanb065 troubleshooting on our units but the issues persists. 

Hisense Roku TV
Roku TV C219X
Software Version 9.4.0 - build 4200-94
System Update: Last Updated Dec 18, Last Checked Feb 24

**Comment by ajbplayluv** [comment]
We are using 10 TCL Tvs. We are also seeing the app close down after 2 hours.  We have tried all settings recommended by Roku.

**Comment by chtaylo2** [comment]
With the recent Roku updated OS, they implemented multiple Bandwidth/power saving features. I should have access to a TCL TV soon, so i'll see if I can duplicate. I'm not able to duplicate using standard Roku players but it wouldn't be the first time a new Roku OS implemented a bug in the TCL TV.

If you are using the PhotoView built in screensaver, does it continue playing after 2 hours? Try to use the slideshows on the screensaver side and see if you can reproduce. That'll help in determining a potential cause.

Have you seen this same issue while using any other apps that are sitting idle?

**Comment by ajbplayluv** [comment]
I only use the photo view app on these tvs.

I wish there would even be a way to roll back the TCL software.

**Comment by wmaclellan** [comment]
Chris, we also only use the Photo View App on our Hisense TVs but I will test the screen saver. 
If there’s another App you’d recommend testing with please let me know and I’ll give it a try.

**Comment by Diaa-G** [comment]
I have exactly to same probleme, photoview leave after 2 hours

**Comment by nathanb065** [comment]
I've been away from work for a few days.  I show up a few hours before we open on the weekends and will test out the screen saver on a TCL and Insignia TV. Hopefully I'll have an update tomorrow morning on this.

**Comment by louisecasey** [comment]
I have the same problem.  I was using Photoview as an all-day presentation medium.  2 hour cutoff makes it pretty useless to me.  If anyone can suggest another app, it would be great.

**Comment by chtaylo2** [comment]
Good news.  I was able to replicate the issue on a TCL tv this weekend and have a work around. I’ll publish a fix for the issue tomorrow and should be approved by Wednesday. 

It’s due to a bug in the Roku TVs and the work around is able to trick it into not triggering the 2 hour time out.  I’ve had this this running for 8 hours and no issues.

**Comment by fieroloki** [comment]
Was just about to post I have the same issue till I noticed your reply.  This would probably work for any Roku device?  We have 1 TCL Roku TV and 4 Roku Expresses on non smart TV's (all having the same issue)

**Comment by chtaylo2** [comment]
@fieroloki - Yes, will apply to any Roku player/devices.

**Comment by chtaylo2** [comment]
Here's the bug fix release if you want to test before it goes live:  https://my.roku.com/account/add/QGGTVR

Please post your findings.  Thx

**Comment by fieroloki** [comment]
> @fieroloki - Yes, will apply to any Roku player/devices.
Sounds good. Thank you! I have them all testing now.

**Comment by fieroloki** [comment]
These all kicked back to the roku home screen right at the 2 hour mark.  When should the v3.7.2 build 620.20210301 be available for update? So far the app isn't showing an update. If it is live, then I need to dig into our firewall logs and see what's being blocked.

**Comment by nathanb065** [comment]
We have currently updated our profile with the Photo View Beta app and are testing as well.  Will comment in a few hours with our findings.  Thanks for the work you put in on this

**Comment by wmaclellan** [comment]
We have loaded the fix to our 7 Hisense Roku TVs and will update in two hours.

**Comment by wmaclellan** [comment]
> We have loaded the fix to our 7 Hisense Roku TVs and will update in two hours.

Slideshows have been on all TVs now for ~4 hours without issue. 

Thank you Chris

**Comment by fieroloki** [comment]
> > We have loaded the fix to our 7 Hisense Roku TVs and will update in two hours.
> 
> Slideshows have been on all TVs now for ~4 hours without issue.
> 
> Thank you Chris

Are you on v3.7.2 build 620.20210301?

**Comment by wmaclellan** [comment]
@fieroloki yes v3.7.2

**Comment by nathanb065** [comment]
Ours have ran for 5 hours. Insignia and TCL. Thanks again for all of it!

**Comment by fieroloki** [comment]
> @fieroloki yes v3.7.2

beta channel? Just trying to make sure our firewall isn't blocking an update

**Comment by wmaclellan** [comment]
@fieroloki yes, beta channel.

They ran without issue for 9 hours yesterday.

**Comment by fieroloki** [comment]
> @fieroloki yes, beta channel.
> 
> They ran without issue for 9 hours yesterday.

OK, thank you! I'll wait on a general release patch

**Comment by fieroloki** [comment]
Hello!  Was curious when the fix will go live for everyone?

**Comment by chtaylo2** [comment]
Roku approved and released it 5 minutes ago.

For business users of this free channel, please take time to donate to continue supporting the development: https://www.photoviewapp.com/donations/

Thanks

**Comment by fieroloki** [comment]
> Roku approved and released it 5 minutes ago.
> 
> For business users of this free channel, please take time to donate to continue supporting the development: https://www.photoviewapp.com/donations/
> 
> Thanks

Thank you!  I will see if i can get them to update, and yes, i plan on donating

**Comment by fieroloki** [comment]
> Roku approved and released it 5 minutes ago.
> 
> For business users of this free channel, please take time to donate to continue supporting the development: https://www.photoviewapp.com/donations/
> 
> Thanks

I think we are golden.

**Comment by louisecasey** [comment]
Thanks!  Works just like I'd hoped.  Louise Casey
 
 
 
-----Original Message-----
