### ISSUE TITLE
No Photos or video

### ISSUE THREAD

**Issue by MrThurtle** [chtaylo2/Roku-GooglePhotos#376]
I've updated Roku, go to your app..it looks like it is reading the photos, but won't display any photos of videos...Tcl roku
![16144931976464191502375037236331](https://user-images.githubusercontent.com/79781380/109409722-312c0f80-7939-11eb-9b94-b0bed23034a6.jpg)

**Comment by MrThurtle** [comment]
Re the problem above...I've been successfully using the app for a few years... Somebody changed something... But I don't think it was me.

**Comment by fieroloki** [comment]
Have uninstalled the app, reinstalled and relinked? Sometimes things just need a good kick.

**Comment by chtaylo2** [comment]
During heavy times of usage, the app wide quota sometimes runs out. It resets a 12:00 am PT. This is a Google Photos API limitation.

**Comment by chtaylo2** [comment]
Closing this as a temporary known issue at times during heavy usage.
