### ISSUE TITLE
Extend the limit for display

### ISSUE THREAD

**Issue by johnnyzzhu** [chtaylo2/Roku-GooglePhotos#381]

**Comment by johnnyzzhu** [comment]
Please increase the time limit for restart the screen saver, currently at 12h. Would it be better to 7days or NEVER?
Especially important to manage for GRANDMA!!!

**Comment by chtaylo2** [comment]
@johnnyzzhu - This is required to reduce usage of people not actively watching.The application already exceeds the quotas set by Google Photos daily.

**Comment by johnnyzzhu** [comment]
Modern day photo apps turn a tv screen into a picture frame. Not sure you need any one “watching” if you have a painting hanging on your wall.  At least have a function to turn itself on in the morning.
Please think outside of the box.
Thanks
John

Sent from my iPhone

On Apr 21, 2021, at 7:06 PM, Chris Taylor ***@***.***> wrote:

﻿

@johnnyzzhu<https://github.com/johnnyzzhu> - This is required to reduce usage of people not actively watching.The application already exceeds the quotas set by Google Photos daily.
