### ISSUE TITLE
Bug: screen goes black between photos

### ISSUE THREAD

**Issue by jtap84** [chtaylo2/Roku-GooglePhotos#384]
Exact same issue as https://github.com/chtaylo2/Roku-GooglePhotos/issues/319

Only difference is that every once in a while, it does go to a photo without going to black. But 98% of the time, it does go black for several seconds between photos.

issue 319 was closed. I tried downloading the bug fix, but when I click "add channel, it goes to a "page not found."

I LOVE this app. I just discovered it actually. 🤷‍♀️ but if I could watch a continuous slideshow of photos without the black, it would be better. 

Thank you!

**Comment by jtap84** [comment]
@chtaylo2

**Comment by chtaylo2** [comment]
This happens sometimes when the app has reached it's global quota for the day. Resets at 12:00 am PT.  Unfortunately, it's a limitation from Google API and applies to all users of the app.

https://www.photoviewapp.com/faq/#timeout
