### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by bmorenico** [chtaylo2/Roku-GooglePhotos#385]
Got a new Roku and tried to link the photo view app and it is giving me the following error code:

An error occurred in 'onNew Token's. Code: -60- SSL certificate problem: certificate has expired

This is over the link page and you cannot see the code.

The only choice below to select is RETRY. If you click okay on RETRY the same error code comes up.

I tried removing then reinstalling and unplugging the Roku to no avail.  

Thanks for the support!!

**Comment by chtaylo2** [comment]
Thanks, should be fixed now.
