### ISSUE TITLE
Screensaver not working

### ISSUE THREAD

**Issue by andreaordodi** [chtaylo2/Roku-GooglePhotos#386]
Installed and chose it as my screensaver in settings but it never comes on.

**Comment by cjsahansra** [comment]
Screensaver also not working for me. Already tried uninstalling and adding again. Keep getting "Screensaver paused" message on bottom corner.

**Comment by chtaylo2** [comment]
@cjsahansra - go into the app screensaver settings and disable HDMI CEC settings. Some TVs have issues with this.

**Comment by chtaylo2** [comment]
@andreaordodi - make sure you have screensaver enabled in the Roku settings. You can also set the wait time for it to come on

**Comment by andreaordodi** [comment]
I have done these things. Also I'm not able to select a specific Google
photo album from the menu. No matter what I select it defaults to all of my
Google photos

**Comment by chtaylo2** [comment]
Here are instructions on how to setup your screensaver and select an album. 

Setup screensaver: https://www.photoviewapp.com/faq/#screensaver-enable
Select specific album: https://www.photoviewapp.com/faq/#screensaver-album

If this doesn't work, i'd recommend in replacing your Roku player.

**Comment by andreaordodi** [comment]
I did select an apple but it still cooling all of the photos. I have a Roku
TV so it replacing it is not that simple and it's not that old

**Comment by andreaordodi** [comment]
Sorry that was supposed to say I did so that's an album but it's still
defaults to all of them

**Comment by andreaordodi** [comment]
Finally figured it out but now it won't let me change the album. Had to
select it and tried to uncheck one of them and it won't save it
