### ISSUE TITLE
Roku channel help docs have many grammatical and spelling errors

### ISSUE THREAD

**Issue by patrick-higgins** [chtaylo2/Roku-GooglePhotos#39]
I'm using the new Roku channel for Google Photos and have found numerous grammatical and spelling errors in the "Tips and Tricks" documentation.

Examples:

- orginize (should be organize)
- which lets will stream your -> which lets you stream your
- more powerful then -> more powerful than
- grandmothers dusty album -> grandmother's dusty album

**Comment by patrick-higgins** [comment]
Largely fixed by #40. Marking this fixed.

**Comment by chtaylo2** [comment]
Moved to release v1.6
