### ISSUE TITLE
PhotoView on Chromecast with Google TV?

### ISSUE THREAD

**Issue by BethTimken** [chtaylo2/Roku-GooglePhotos#391]
Hi Chris, I have immensely enjoy your PhotoView screensaver on Roku for years. Thank you, _brilliant_! 

We have recently switched to Chromecast with Google TV. Will PhotoView with here too? I haven't been able to see how. The Google screensaver for Google Photos is inferior you yours.

Thanks!

**Comment by chtaylo2** [comment]
I'm sorry but this channel is only on the Roku device. Glad you like it on Roku.
