### ISSUE TITLE
Screensaver paused every time

### ISSUE THREAD

**Issue by itzme1234** [chtaylo2/Roku-GooglePhotos#393]
Photo View seems to work fine in the channel, but I also have it set as My Screensaver. My Roku stays on and I use multiple streaming devices. Ever time I change to my Roku input I have a black screen and “screensaver paused” message.

sometimes the message is that’s phots “expired”

I’d like it always be rotating through photos.

**Comment by itzme1234** [comment]
To clarify, the error message on the black screen is:  Screensaver has expired after 12 hours

**Comment by chtaylo2** [comment]
Please see here: https://www.photoviewapp.com/faq/#timeout
