### ISSUE TITLE
Emojis in album names are not displayed

### ISSUE THREAD

**Issue by toddbutters** [chtaylo2/Roku-GooglePhotos#395]
Just an FYI. Thank you for making it easy to show my family photos to my family.

Issue: Emoji's are not displayed correctly in album names.
What's expected: Emoji's are displayed correctly.
What happens: [X] is shown.

Steps to Reproduce: 
1. Create  an album in Google Photos containing any emoji in the name. I tested the first smile face, grinning face, and the Canadian Flag.
2. Open Photo View and browse to the album containing emoji.
3. Photo View will not render the emoji and just output a missing image [X] symbol.

Model: 4640X - Roku Ultra
Version: 10.0.0 - build 4209-29

**Comment by chtaylo2** [comment]
Unfortunately this is a limitation of the character set on the Roku device. Roku's do not have the ability to decipher Emoji's in the title.  Thanks for using the app
