### ISSUE TITLE
Reduce or remove black space 

### ISSUE THREAD

**Issue by kupernatik** [chtaylo2/Roku-GooglePhotos#398]
Is there a way in the app to have it place 2 images side by side so there is no black space on the sides?  This is how it works on the chrome cast. Thanks

**Comment by chtaylo2** [comment]
There's no way to add two photos side-by-side, but you can add a background "blur" which removes the black spaces around the photos. Go into settings and Display type.

**Comment by kupernatik** [comment]
Thanks, I knew about that feature and is what we currently use. Was just seeing if the 2 images would be an option or if it was a limitation on the Google API or something. Thanks for the great app btw.
