### ISSUE TITLE
App won’t load

### ISSUE THREAD

**Issue by wmaclellan** [chtaylo2/Roku-GooglePhotos#402]
This morning the app would not load on any of the TVs in our store or the test unit we have offsite. Checked version and received notification that the App was up to date. 
Deleted the reinstalled App. 
Now receiving following error on launch: An Error Occurred in ‘onNew Token’. Code 406 - the requested URL returned error: 406 
“Retry” results in the same error. 

Hisense 55” TVs
PhotoView Ver 5.620 build 20210301 (before and after reload) 
Roku TV: C227X
Software Ver 10.5.0 build 4210-94

**Comment by nathanb065** [comment]
Same issues for me. 5 insignia 32" Roku TVs. TVs have been up to date for a month, app is up to date. Once the app is selected, it is force closed back to the home screen. Have not tried reinstalling app but I assume it would throw the same error. 

Thanks for posting this and thank you Chris for the work you put in on the app.

**Comment by Diaa-G** [comment]
Same Here, the app load, but exit immedialty...

thank you Chris for the work you put in on the app

**Comment by chtaylo2** [comment]
Should be working now.  Was some server issues with the API.

**Comment by chtaylo2** [comment]
Well... It's working mostly. Still some lingering issues.

**Comment by Diaa-G** [comment]
> Should be working now. Was some server issues with the API.

thanks a lot !!

**Comment by wmaclellan** [comment]
> 

All working for us. Thanks for the quick weekend turnaround.

**Comment by nathanb065** [comment]
Good here as well. Agreed, thank you a ton!
