### ISSUE TITLE
Code: -60- SSL Certificate Problem

### ISSUE THREAD

**Issue by rmmugge** [chtaylo2/Roku-GooglePhotos#403]
Hi, we've been occasionally getting this error the last 4-5 days. Sorry for the weird photo, but what was sent to me was weirder before I cleaned it up some.

![image](https://user-images.githubusercontent.com/98196317/151203022-5753f3b4-95f8-4ff0-a316-42514e3f68e2.png)

**Comment by chtaylo2** [comment]
This was fixed
