### ISSUE TITLE
New videos will not play

### ISSUE THREAD

**Issue by calthouse01** [chtaylo2/Roku-GooglePhotos#418]
Why won't recently uploaded videos play in the Photoview app? I had trouble playing one newly uploaded video, it wouldn't play until almost an hour later. Now I've got one I uploaded LAST NIGHT and it STILL WON'T PLAY! Every time I click on it, it just immediately aborts playback. First I thought it was an issue with it being compressed, except I have other compressed videos uploaded that playback PERFECTLY, but I went ahead and re-uploaded it as uncompressed and it STILL WON'T PLAY. Uninstalling and reinstalling the app does nothing and there's no updates available for the app. Videos are in .mp3 format which should be just fine...SO WHY WON'T YOU LET ME PLAY MY VIDEOS?! FIX...THIS...NOW!!!! 😡😡😡

**Comment by chtaylo2** [comment]
Ok. Nice way to ask for assistance on a free app
