### ISSUE TITLE
Pictures from Drive?

### ISSUE THREAD

**Issue by mmlmrx** [chtaylo2/Roku-GooglePhotos#419]
Hi,
  Google Photos doesn't have a great sync experience from mobile devices - it won't let me sync folders on my phone to online albums.  There are better third-party sync options for Drive.  Since your tool already has Google authentication, could it also read from Drive folders?

**Comment by chtaylo2** [comment]
Google Photos app has a great sync functionality. I would suggest this.

**Comment by mmlmrx** [comment]
I'm not sure you read the full question. If I have a separate folder of wallpapers, and I ask Google Photos to sync that folder, it dumps them into the same big bucket that it keeps my camera photos. I don't want all of my camera photos displayed on my tv - just the wallpapers. So for every picture I add to that folder on my phone, I would then have to manually go into the Photos app and add each picture to a separate "wallpapers" album. Drive sync doesn't do that - it syncs local files with matching online folders and subfolders.
