### ISSUE TITLE
Feature request - vertical TV 

### ISSUE THREAD

**Issue by srsoderberg** [chtaylo2/Roku-GooglePhotos#421]
Would love to hang a TV vertically.  I'm new to the GooglePhotoApp - there might be a way to do this already.  Guidance?

**Comment by pinovecs** [comment]
The application is tied to the display that the Roku provides.  I don't believe the Roku supports vertical.

**Comment by chtaylo2** [comment]
This is not a feature that will be built into the application. You could optionally change the orientation of the photos in Google Photos and it will show them as vertical. 

Select photo > Three dots > Rotate Left
