### ISSUE TITLE
Multiple devices

### ISSUE THREAD

**Issue by Itcame2pass** [chtaylo2/Roku-GooglePhotos#426]
Up until recently I was able to be signed into photo view on all my roku devices. It appears I can only be signed into one device at a time now. Has a limit been placed on the number of devices that now can be linked? This has been very frustrating. 
Thanks,  
Itcame2pass@yahoo.com

**Comment by pinovecs** [comment]
I'm using multiple devices at the same time right now and have no issues. (2 devices same account and photos)

**Comment by Itcame2pass** [comment]
Up until recently I had been using the app on multiple Roku's in two different locations (different networks) with no issues. The last month and half I can only be signed into one Roku without being kicked off the other devices.  
Strange. I have used this app for at least the last 5 years in the same way with no issues.
Mark
    On Thursday, September 8, 2022 at 02:26:25 PM EDT, Chris ***@***.***> wrote:  
 
 


I'm using multiple devices at the same time right now and have no issues. (2 devices same account and photos)

**Comment by chtaylo2** [comment]
There is no limitation on the number of devices you can link to your account. This is only controlled by Google and if/when you grant the application access.
