### ISSUE TITLE
Won't let me register

### ISSUE THREAD

**Issue by Mimilikestreats** [chtaylo2/Roku-GooglePhotos#429]
I downloaded the app on my Roku but it won't let me register.
The code pops up but times out too fast for me to key it into the website.
Error - Json error response: [onCheckAuth] Invalid code
It literally is valid for only a few seconds before it times out and gives me that message.
When I click on Get a New Code it just does the same exact thing over and over.
Any help is appreciated.
Thanks

**Comment by salmoidforwork** [comment]
I have the same problem. Keep getting `Error - Json error response: [onCheckAuth] Invalid code`

**Comment by chtaylo2** [comment]
Try now. Looks like was some issues with the linkage API. Should be good now.
