### ISSUE TITLE
Screensaver in paused mode when turn TV/Roku back on

### ISSUE THREAD

**Issue by pruchkin2** [chtaylo2/Roku-GooglePhotos#435]
Not a big deal but be nice if it woke up as soon as Roku came on.  Using App version 3.7.  Thanks much

**Comment by chtaylo2** [comment]
@pruchkin2 - The screensaver is put into paused mode when a device is powered off due to HDMI-CEC controls. Unfortunately, there is no signal that's sent to the HDMI-CEC controls on the device when power is restored. A key press is required.

Thanks
