### ISSUE TITLE
Channel components deprecated in 2018 - *IMPORTANT*

### ISSUE THREAD

**Issue by chtaylo2** [chtaylo2/Roku-GooglePhotos#44]
The following components used in the GooglePhotos channel will no longer be supported including:  roSlideShow, roGridScreen, roPosterScreen, roSearchHistory, roSearchScreen, roPinEntryDialog

XX component is no longer updated and will be deprecated on January 1st, 2019.
Beginning July 1st, 2017, any new channels using this component will be rejected during certification.
Beginning January 1st, 2018, any updates to existing channels using this component will be rejected during certification.

Will need to move all components to SceneGraph.

**Comment by timrit** [comment]
Chris,
Not a developer, but really want to see PhotoView be successful on Roku.  Based on your Feb 6 comments and your knowledge of Google Photos, what is the future of PhotoView and Roku access to Google Photos going forward?  Thanks!

**Comment by chtaylo2** [comment]
Timrit, thanks for the note.  Roku is moving away from some of their screens in 2018/2019.  I expect to have something out this summer or fall to move the channel away from legacy components.  Stay tuned! Great to hear you like the channel

**Comment by cbandy** [comment]
Article with some links to docs and migration suggestions: https://blog.roku.com/developer/2017/02/01/legacy-sdk/

**Comment by chtaylo2** [comment]
Beta version: https://my.roku.com/account/add?channel=RZ5TQ6
