### ISSUE TITLE
Registration:Json error response [onCheckAuth] invalid location 

### ISSUE THREAD

**Issue by bcbeatty** [chtaylo2/Roku-GooglePhotos#440]
Error occurs after about 10 seconds. 
Code will work if typed in fast enough. But tv will not accept authentication.

**Comment by bcbeatty** [comment]
![Uploading image.jpg…]()

**Comment by narutter** [comment]
I have the same issue.  Roku keeps showing the same error as bcbeatty stated, even when approval is granted online.

**Comment by chtaylo2** [comment]
What device model are you using?  I’ve not been able to reproduce this issue.

**Comment by narutter** [comment]
Roku model 392X - Roku Premiere

This had worked in the past.  I tried rebooting the Roku and checked
PhotoView for any updates.

When I open PhotoView, it displays the screen to link this Roku to your
Google account.  If I do nothing and just wait about 30 seconds, the "ERROR
- Json error response :[onCheckAuth] Invalid location" error displays along
with "Retry".

If I enter the code quickly on my laptop, it appears to accept it and grant
access.  I even get a verification email that I've granted access.  But
PhotoView just goes to that same error screen.

I hope you can fix this as I would love to view my photos on my TV.  Thanks.
Nancy

**Comment by bcbeatty** [comment]
I have a Roku TV TLC 65S555 software version 11.5.0 build 4317-dk
I also have a 55” same issue.

**Comment by narutter** [comment]
Any progress on this?

**Comment by narutter** [comment]
Hi.  Any progress on this issue?

**Comment by bcbeatty** [comment]
This seems to be working for me. 
my Roku is showing pictures and slideshow from my google pics.
