### ISSUE TITLE
Screensaver DOES NOT SAVE YOUR SCREEN!

### ISSUE THREAD

**Issue by wayneb64** [chtaylo2/Roku-GooglePhotos#441]
Please fix the pausing issues and the PERMANENT TEXT "Photo View" which will end up burning into your screen, same for the paused message when the thing dies, which is constantly. 

I was really excited to get a decent screen saver after my favorite, 4K Nights (or something like that) was removed recently. Now I am stuck with Roku Photo Stream which you cannot change at all and keeps putting up the QR code annoyingly BUT it ACTUALLY SAVES MY SCREEN.

**Comment by chtaylo2** [comment]
The pause screen and the logo rotate very 20 minutes. It won't burn in.

**Comment by wayneb64** [comment]
What do you mean rotate? 
Every time I turn on my TV, the screensaver has 'failed'/paused and instead of seeing my images I see all black, did you fix that?
