### ISSUE TITLE
OAuth2 polling request failed

### ISSUE THREAD

**Issue by rjmorrow** [chtaylo2/Roku-GooglePhotos#45]
Using a Roku Stick, whenever I enter the Google Photos app, I am asked to re-register my Google Photos account with the device.
First attempt fails, and gives me error message: "OAuth2 polling request failed. Missing User Data"
I select "Try again" and register the device a second time, only to get the message that my account has already been linked to the device, and from there, I can access the photo albums.
However, the registration does not stick, and I have to go through the whole process again any time I leave the app.
Have have two other Roku TV's running the same app and they are not having this problem.
Thank you.

**Comment by chtaylo2** [comment]
This is a known issue affecting some users. Release 1.6 was pushed early last week, but Roku is taking their time approving. Hoping it'll be approved this week and will resolve your issue. You'll know it's been released as a "New Features Popup" will display when opening the channel.

Thanks for reporting the issue
Chris

**Comment by rjmorrow** [comment]
Thank you for your quick response. Release 1.6 hit my devices yesterday
afternoon. Everything is up and running perfectly. Thanks again!


*Randy Morrow*
Security Coordinator and IT Support
Tri-City Christian School
www.tccs.org
office: 760-630-8227 x210
cell: 760-505-1752
