### ISSUE TITLE
Cannot Reregister / Register

### ISSUE THREAD

**Issue by AllanZach** [chtaylo2/Roku-GooglePhotos#452]
I used RokuPhoto View in the past. I went to use it again and "it" required re-registration. I went to the URL required and attempted to put in the 6 digit code. I did this first on my Android phone (a Pixel 6a with all updates current) and then on my Chromebook. Neither worked. On the phone putting in the 6 digits resulted in the "register" button not doing anything, no matter how many clicks. It was _not grayed out. Then on the Chromebook, for some reason the 6 digits would not enter in the fields, multiple attempts resulted in unusual results (only "9's" showing up in the field, the alpha digits not showing up). Grrrrr, I want to use this again! Please help

**Comment by AllanZach** [comment]
PS I have updated everything, the Chromebook, Pixel 6a have been updated and I have reset the Roku Ultra - all updated.

**Comment by chtaylo2** [comment]
There was a DB issue which has been fixed. Please try again

**Comment by chtaylo2** [comment]
Closing
