### ISSUE TITLE
New Roku update breaks the settings to the screensaver.

### ISSUE THREAD

**Issue by TimL1752** [chtaylo2/Roku-GooglePhotos#473]
Due to the newest Roku update, they altered how a user accesses wallpaper and theme settings. Before, they were done using an option that linked to a specific menu of the app, but now the update has all settings done in the app, but the screensaver setting are inaccessible.

**Comment by shass-git** [comment]
I have noticed that too on my new Roku TV which I had to get when the old one died.  And it's more weird than that.  When I first set up the TV and installed the Photoview app, all was as it was before.  A short time later, the menus on the TV were different.  It used to be Settings > Themes , but switched to Settings > Wallpapers & screensavers.  Then Photoview was not listed as a screensaver so I could not get to the options to select folders, etc.

Then for an unrelated reason (perhaps unrelated) I did a factory reset of the TV and it was displaying as before.  But after the screensaver starting correctly a few times, the TV later rebooted when the screensaver started.  The behavior is odd and unpredictable.  I also suspect that a recent Roku update made the screensaver no longer 100% compatible.
