### ISSUE TITLE
Registration error

### ISSUE THREAD

**Issue by chrismv48** [chtaylo2/Roku-GooglePhotos#477]
Here's the order of events:

1. Open the PhotoView app on Roku, greeted by the registration page
2. Enter the provided code on https://www.photoviewapp.com/link
3. It takes nearly a full minute for a response
4. While waiting for the response, PhotoView app eventually gives the error:
```
An Error Occurred in 'onCheckAuth'. Code: 500 - The requested URL returned error: 500
```
5. The request finally succeeds on the website and I'm able to grant access to the app.
6. PhotoView doesn't acknowledge this and instead continues to show the registration page (even after opening and closing the app).

**Comment by Craigwoods5** [comment]
Having same issue and can't sign in

**Comment by chtaylo2** [comment]
Please try again
