### ISSUE TITLE
API Error: Invalid return code from Google API

### ISSUE THREAD

**Issue by timrit** [chtaylo2/Roku-GooglePhotos#50]
Get this in all aspects of the Roku app. Albums, Search, and slideshow.  The only thing that kind of works is the screensaver, but it only seems to show maybe two dozen pics and these are typically ones just recently taken on my phone that are automatically downloaded to Photos. 

Was reading previous closed issue that looked like increasing the timeout fixed the issue. I have 96000 pics and hundreds of albums. Any ideas?

**Comment by lp27** [comment]
I am getting the error.  How do I set the timeout longer?

**Comment by chtaylo2** [comment]
This should be fixed with v2.0.  You can see the beta version here: https://my.roku.com/account/add?channel=RZ5TQ6
