### ISSUE TITLE
People, Places and other missing albums?

### ISSUE THREAD

**Issue by wspies721** [chtaylo2/Roku-GooglePhotos#51]
This app is probably the best Google Photos app I have found.  However,  it seems to only work within the constraint of albums I have manually created myself on my Google Photos site.  Why does it not show those automatically created albums Google nicely creates for us -- like the People album or Places album?

**Comment by chtaylo2** [comment]
Hi,  Would love to add this in, however Google has limited what the old Picasa API allows use to pull.  See: https://developers.google.com/picasa-web/faq.

Official stance from Google:

>> If you are logged in as the owner of the content, you can retrieve all of the photos you've uploaded and albums you've created in Google Photos and Picasa Web Albums via the Picasa Web Albums Data API. There are some exceptions. For example, Google Photos "Shared Albums" are not available via this API. There are no plans to add support for all Google Photos features to the Picasa Web Albums Data API.

It's unfortunate. Maybe in the future!

**Comment by wspies721** [comment]
Well -- so Google doesn't suck :)  I love Google Photos -- but their integration really should be opened up.
