### ISSUE TITLE
Feature Request: Support selecting albums to use in the screensaver

### ISSUE THREAD

**Issue by deviantintegral** [chtaylo2/Roku-GooglePhotos#52]
With Photos integration on the Chromecast, you have to select specific albums to display. I think for most people, showing all photos randomly is good. However, I really liked being able to limit the slideshow to photos that we'd curated and shared. Any thoughts on adding this as a feature?

**Comment by demornay** [comment]
Excellent Roku app, Chris - yes I'd love to have this feature too

**Comment by brandilton** [comment]
would love this feature too, I never really prune my pictures so lots of boring pics that i'd prefer not to be on the screensaver.  being able to point to an album(s) of favorite pics would be awesome!

**Comment by tbattreall** [comment]
Thumbs up...  The one thing ChromeCast and Amazon fire have over Roku is awesome screensavers.  But your app could resolve this shortcoming with this feature.  If the screensaver could be limited to a folder then a user could download the same images Chromecast has (https://gist.github.com/dconnolly/8188825)  or Amazon fire has (https://mega.co.nz/#F!thFw3aLY!OWSR9oW5BXNHdbm3No19iw) and then upload those into a custom album and make that album the Roku screensaver. In fact, you could setup a single public album with these pictures and then make this a setting for the users to use these albums.

**Comment by DuncanMack** [comment]
I'd love to make a plug for this, too, and wish I could help make it happen. My photo collection is a huge assortment ranging from the sentimental to the practical (e.g. a can of paint whose color I want to remember). At the moment the proverbial can of paint pops up alongside my more meaningful photos. Being able to point to an album as a source would be fantastic.

**Comment by acorelis** [comment]
Agreed with all the above comments.  Your app is great, this additional feature would make it phenomenal.

**Comment by chtaylo2** [comment]
Targeted for inclusion in the new version, during the move over to screen graphs.

**Comment by arnoldsmyth** [comment]
Great to hear that this is targeted for inclusion. I came to request this as a feature.

**Comment by madysondesigns** [comment]
Another vote for this feature!

**Comment by chtaylo2** [comment]
This much requested feature as made it into the v2.0 release!  You can check out the BETA VERSION here: https://my.roku.com/account/add?channel=RZ5TQ6

Testing is continuing and will be published to the public channel soon.
