### ISSUE TITLE
One photo at a time?

### ISSUE THREAD

**Issue by dabrenTO** [chtaylo2/Roku-GooglePhotos#53]
Hello. Is there any way to show just one photo as opposed to a slideshow? Or to browse and look at photos to show others without creating a slideshow?

**Comment by chtaylo2** [comment]
You can select a photo in the "browse photos" after select an album. You don't have to start a slide show to see all the photos included. Once you found a photo you want to see, you can select and then hit "Play/Pause" to stay on that single photo.

Thanks
