### ISSUE TITLE
Feature request: shuffle album photos

### ISSUE THREAD

**Issue by dpawlows** [chtaylo2/Roku-GooglePhotos#55]
You have the shuffle all photos option, but it would be nice to be able to shuffle photos within 1 album (or better yet, select x number of albums and shuffle from those).  

Thanks for creating the channel!

**Comment by chtaylo2** [comment]
Targeted for inclusion in the new version, during the move over to screen graphs.

**Comment by chtaylo2** [comment]
Beta version available : https://my.roku.com/account/add?channel=RZ5TQ6
