### ISSUE TITLE
Screensaver only showing most recent photos/album

### ISSUE THREAD

**Issue by groke** [chtaylo2/Roku-GooglePhotos#56]
Thanks for the great app! I want to use it primarily for the screensaver function, however it seems the screensaver is limited to the first album, or maybe the latest X pictures. Can it show pictures from multiple albums, or from everything?

Running on Roku 3

**Comment by sjhnny** [comment]
I concur! This is a great  app, thanks for building it. I'd like additional screensaver options, such as a seeing random photos from my entire photo collection.

**Comment by chtaylo2** [comment]
Thats correct. It does limit the photos to 500 (then loops) but does select them from random albums. This is to help reduce the API calls to the Google API as some folks have 100's / even 1000's of albums. Each album pulled from is another API call. The idea has been floated around to allow ongoing querys.. however, we have to be careful that Google doesn't cut our API access.

**Comment by Eserim** [comment]
Chris - are you sure about the "select them from random albums" bit?  As I've only ever seen ones selected from the most recent photos.  
Great App BTW.

**Comment by jondgrant** [comment]
I too would love to see more variety in the photos selected for the screensaver.  Of my 10 years worth of photos, the vast majority of photos shown are from the last few months.  Thanks for a great app Chris, it has really brought to life our family photo collection. My kids love it.

**Comment by 0newolf** [comment]
So when I view random photos in the app, it is very random. But in screen saver mode, not at all, just one recent album. Random is random, why treat random view within the channel different from random view within screen saver?

**Comment by guyadam** [comment]
Great app! like the previous comments, I only see most recent photos in the screensaver. If it would show truly "random" photos from all photo's via the screensaver this app would be amazing. (6 stars)

**Comment by Eserim** [comment]
I'm not sure if this is still an active app.  I'm no Andorid developer but have just taken a look at the code.  It looks like it is set to take 300 Random Pictures or 500 latest - there is a if statement in the code that seems to be being ignored

>         'If userIndex is set to 100, means user wants random photos from each linked account shown. 
>         if userIndex=100 then
>  ...
 
With Userindex being set earlier based on the ssUser variable - which appears in just the ScreenSaver code (2 files) there seems to be a separate Screen Saver Serttings routine, which sets this, but not one I've seen in use.

**Comment by chtaylo2** [comment]
Thats correct @Eserim. It will show the latest 500 photos.  This was done to limit the API calls to Google. The thought here was to help reduce API calls to Google so they don't block our API access. Some folks have 1000's of albums and some have 1 or 2; so there's not a single "right" way to do this.  Will give this some thought.

Thanks for the feedback!

**Comment by Eserim** [comment]
Chris - thanks for getting back to us - I understand the API hit  - would it not be possible to randomly select 500 images when the screen saver kicks off from the entire library, then display those in sequence?

Back in the Picasa day, I guess you could pick friom the Picasa Screen Saver album - why did Google kill a brilliant program without adequate replacement?

**Comment by timrit** [comment]
Chris,
I added another Google Photos Account a few days ago and today I switched back to my “regular” account. For some reason the PhotoView Roku screensaver seems to only want to pick a random little league game pics from 2012 instead of my most recent pics.  Any ideas or workarounds I should try.

**Comment by chtaylo2** [comment]
This is a known issue.  Looks like something changed with the Google API over the weekend. I'm looking into it and tracking here: https://github.com/chtaylo2/Roku-GooglePhotos/issues/65    

Thanks for the feedback.

**Comment by timrit** [comment]
Thanks Chris!  BTW the Roku App is now able to pull up all of my voluminous albums and pics thanks (I think) to the pagination feature that you have added...

**Comment by chtaylo2** [comment]
Closing issue. This has been fixed in Release 1.7 (https://github.com/chtaylo2/Roku-GooglePhotos/releases/tag/1.7)  Update has been pushed to Roku for publishing.
