### ISSUE TITLE
Order of photos

### ISSUE THREAD

**Issue by cheryl28** [chtaylo2/Roku-GooglePhotos#57]
The order of the photos are being shown by the date the pic was created, not the order by which i manually put them in within my album.  Can this be corrected?

**Comment by chtaylo2** [comment]
This might be possible via the API. Will add to the backlog.

**Comment by cheryl28** [comment]
Thank you.  Also is there a way to have the pictures and video in one folder?

**Comment by chtaylo2** [comment]
I looked at this tonight and confirmed that photos are showing in the order placed in the album. I'm not sure why they would not be for you.

**Comment by chtaylo2** [comment]
Closing this for now. This appears to be working.
