### ISSUE TITLE
Photoview is showing photos NOT in Google Photos

### ISSUE THREAD

**Issue by ucctgg** [chtaylo2/Roku-GooglePhotos#62]
I removed All photos from my Google Photos.  When I go into Google Photos and click on Photos I see no photos.   BUT, when I go to Roku PhotoView I see eleven photos, when I should be seeing nothing.

**Comment by chtaylo2** [comment]
There are some photos it shows of cats when no account is linked. If you have an account linked and it's showing photos, its you photos. Outside the unlinked account photos of cats, there are no magical photos.
