### ISSUE TITLE
Screensaver is displaying cat photos from Dev Google account

### ISSUE THREAD

**Issue by dagda88** [chtaylo2/Roku-GooglePhotos#63]
I'm able to link my Google account no problem and view my photos but the screensaver is displaying photos from the "ctaylor" Google account. Nice cats.

**Comment by chtaylo2** [comment]
It does this when there is no account linked. Once linked, go to screensaver settings and make sure it shows your account name.

**Comment by dagda88** [comment]
![20171028_183059](https://user-images.githubusercontent.com/33186375/32139104-9026d8a8-bc0e-11e7-837a-7a774666c601.jpg)

![20171028_182644](https://user-images.githubusercontent.com/33186375/32139106-945e5400-bc0e-11e7-89dc-ccca06034b0c.jpg)

I'm the 2nd user to report this issue on https://www.rokuguide.com/channels/photoview-for-google-photos. I hadn't changed any settings before it stopped working.
