### ISSUE TITLE
Screensaver on roku3 not showing linked account photos

### ISSUE THREAD

**Issue by pmarrone1** [chtaylo2/Roku-GooglePhotos#64]
This just started today 10/28.  The screensaver no longer shows my linked account photos. The photos that appear are the default app photos of a cat and the app logo. I've tried reinstalling the app and linking my account but the issue still occurs.

**Comment by abap9000** [comment]
Same exact situation here.

**Comment by w00k-** [comment]
Ok, same here. Glad I'm not going crazy. I tried unlinking it from my Google account, and setting it back up.  I'm using a Roku TV.

**Comment by mikelmartin** [comment]
I am seeing the same behavior.  I have more than one account linked, if I switch to the second account it seems to work. Also if I go to the app and browse or run slide show it works. It is only the screen saver that appears affected
Very strange.

**Comment by dagda88** [comment]
Same situation here. I attempted Mikel's solution but the screensaver still only shows the default/cat photos.

**Comment by pikefloyd** [comment]
I have the same problem too (only affects the screensaver.)

Single account displays cats and app logo. Two accounts shows a picture of a church, (not my photo).

**Comment by jamesdebra** [comment]
I have the same problem too only shows cats

**Comment by abap9000** [comment]
I tried multiple accounts - one account will get a single picture consistently but nothing else.

**Comment by avanrider** [comment]
Same issue here, but now a nebula and I think an art gallery.

**Comment by chtaylo2** [comment]
Thanks for the feedback.  I'm looking into the issue.

**Comment by chtaylo2** [comment]
Update: Something happened with Google's API and they (Google) is not returning random images as of this weekend. You can see this by looking at: https://picasaweb.google.com/data/feed/api/user/default?kind=photo&max-results=500&v=3.0    This should be returning many images, but it's not.  Looking into.

**Comment by chtaylo2** [comment]
Closing issue. This has been fixed in Release 1.7 (https://github.com/chtaylo2/Roku-GooglePhotos/releases/tag/1.7)  Update has been pushed to Roku for publishing.
