### ISSUE TITLE
Screensaver won't use my pictures

### ISSUE THREAD

**Issue by mgb74** [chtaylo2/Roku-GooglePhotos#68]
I have my pictures on Google Photo View which I access through Roku. I set my screensaver to use my photos. Everything was going along just fine until last week when the screensaver started using pictures from Chris Taylor (a bunch of pics of a fat cat + some ocean pics, etc.).
When I went in to hopefully reset the screensaver it just tells me I'm watching my own pics.
I am not, however, having any problem adding new pictures to my albums or viewing my pictures (except of course in the screensaver)

**Comment by chtaylo2** [comment]
This is already being tracked in multiple other tickets. 

Closing issue, was due to an unannounced change in Google API.. This has been fixed in Release 1.7 (https://github.com/chtaylo2/Roku-GooglePhotos/releases/tag/1.7) Update has been pushed to Roku for publishing.
