### ISSUE TITLE
Feature Request: More info regarding screensaver

### ISSUE THREAD

**Issue by rewallac** [chtaylo2/Roku-GooglePhotos#74]
It would be nice if there was an FAQ or How This Works section in the screensaver settings. I know that it pulls random photos from account(s), but I believe there are limitations, does it randomly pull from ALL photos, or only a certain number? Is there any other info that can be provided as to how the screensaver works?

**Comment by chtaylo2** [comment]
Thanks for the recommendation. The channel is going through a complete rewrite to support the new Roku coding requirements. Will look at adding some FAQ around the screensaver. 

Today, the sreensaver will pull 500 random photos from 5 random albums from each user selected.

**Comment by rewallac** [comment]
Any updates on adding the FAQ about the screensaver?

**Comment by danmarker7** [comment]
It would be nice if there was an option to remove there photoview icon.

**Comment by chtaylo2** [comment]
FAQ has been created on the main website. This will continue to be updated with other questions people get: http://www.photoviewapp.com/faq
