### ISSUE TITLE
Feature Request: This day in history

### ISSUE THREAD

**Issue by rewallac** [chtaylo2/Roku-GooglePhotos#75]
Is there any way to have a This Day in History option for the screensaver?

**Comment by chtaylo2** [comment]
Can you provide more details?

**Comment by rewallac** [comment]
Provide an alternate option for a screensaver that shows photos from this day in the past. For example, today that option would show all photos in my account that were taken on January 17th, regardless of the year. (A subtle graphic displaying date of the photo would be nice, but not critical).

**Comment by timrit** [comment]
I'll second that.  To give you a real world example.  My son had his birthday recently and I did a search for his birthdate and had that run as a slideshow.  As a further enhancement, have the date be a range:
--This day in History
--This day in History (3 day bracket)
--This week in History (7 day bracket)
--This month in History
--etc

**Comment by chtaylo2** [comment]
Thanks for the comments. This will not make the v2.0 release but can investigate for a future release.

**Comment by rewallac** [comment]
Any updates on adding this feature?

**Comment by chtaylo2** [comment]
@rewallac -- No work has been done on this yet. Focus was put into a full app re-write this year and since has been on the new Google API coming out. Unfortunately, that's stalled due to no TV link integration...yet. 

I still like the idea, hopefully I can look more into it soon.

**Comment by chtaylo2** [comment]
Added to v2.3 target release

**Comment by chtaylo2** [comment]
Completed. Tagged to v2.3
