### ISSUE TITLE
Hide albums and photos from app?

### ISSUE THREAD

**Issue by cssagogo** [chtaylo2/Roku-GooglePhotos#76]
I feel like during initial setup there was something about this, but cannot find in tips and tricks.  If not, maybe including private in album name and not showing archived photos

**Comment by arnoldsmyth** [comment]
I saw this too when I set up a few minutes ago. It said to include the word private in the title to hide an album.

There is a feature (#52) being included in a future release that will allow you to select a specific album to display.

**Comment by chtaylo2** [comment]
@cssagogo you can see the release note here: https://github.com/chtaylo2/Roku-GooglePhotos/releases/tag/1.7.   Including "Private" in an album name will remove it from displaying. Keep in mind however, it doesn't remove it from the searching.

**Comment by chtaylo2** [comment]
@arnoldsmyth - The channel is going through a complete rewrite to support the new Roku coding requirements. MVP is 90% completed. #52 will likely not make it into the first (v2.0) release, but likely in a future release.  Many, MANY people like the multi-scrolling photos and that will be an available feature directly in the channel when you display any album.

**Comment by chtaylo2** [comment]
Beta version: https://my.roku.com/account/add?channel=RZ5TQ6

Note: While photos and albums are hidden which are tagged with "Private" or "Hangout", the channel cannot remove the items from the Google Time Line. a.k.a Auto Backup.  This is due to how Google Photos stores your images.
