### ISSUE TITLE
Feature Request: Setting to fill screen completely in slideshow

### ISSUE THREAD

**Issue by umichscoots** [chtaylo2/Roku-GooglePhotos#77]
Currently photos in a slideshow are shown letterboxed if they are not the same aspect ratio of the screen they are on.  Provide an option in settings to show the pictures filling the screen.

**Comment by Spacemanspiff-03** [comment]
I agree with this wholeheartedly. I've been looking for awhile now for an application on my roku to do this. I'm not sure if its specific to 4k but even at the proper resolution, the photos do not fill the screen. That and being able to specify the album would make this app perfect for me.

**Comment by chtaylo2** [comment]
If you are on a 4K TV are you sure you have FHD selected in settings? Settings > Set Photo Download Resolution > Full High Def.

This should make the photos full the screen, at least on one side.  However, it doesn't stretch the photos nor zoom.

**Comment by Spacemanspiff-03** [comment]
Hi Chris,

Thanks for taking the time to look into this, I appreciate it. I did make
sure to select FHD in the app options. And I also made sure of the
resolution of the photos themselves. I tried both 4k and 8k resolutions and
neither filled my 4k tv.

I tested it via usb and it worked fine. I would prefer to use your app
though and have all my stuff in one.

Justin

**Comment by chtaylo2** [comment]
Thanks for the details. I can confirm in fact, its scaling to 1600 vs 1920 (FHD). This will be fixed in the upcoming v2.0 release. This new release is a rewrite from the ground up, so many new features. Once I have a beta version, I'll post it here so you can test if you wouldn't might.

Thanks

**Comment by Spacemanspiff-03** [comment]
Okay awesome. Again thanks for keeping me in the loop and following up,
much appreciated. I wouldn't mind testing that out at all. Any sort of a
rough release timeline or too early to say?

Justin

**Comment by chtaylo2** [comment]
Here is the beta version - v2.0: https://my.roku.com/account/add?channel=RZ5TQ6

Please let me know if that solves your issue.

**Comment by Spacemanspiff-03** [comment]
Just gave it a shot. It appears to be displaying at the correct resolution
now. Or at trlhe very least now fills the screen. So I'd say it's a
success. Job well done

**Comment by chtaylo2** [comment]
Great to hear.  This will be released soon
