### ISSUE TITLE
Feature Request: Choose album for screensaver

### ISSUE THREAD

**Issue by mhhursh** [chtaylo2/Roku-GooglePhotos#96]
Would love to be able to set a flag on albums as to whether they should be in the screensaver or not.  

Thanks again for an awesome channel for Roku!

**Comment by chtaylo2** [comment]
This is in the current version already, v2.0.1  

Under Screensaver > Custom Settings > Select Linked User > Directions on Screen.

Thanks
/Chris

Original request:
https://github.com/chtaylo2/Roku-GooglePhotos/issues/52
