### ISSUE TITLE
great app, now missing filenames, search doesn't return all files containing string

### ISSUE THREAD

**Issue by tonylang26** [chtaylo2/Roku-GooglePhotos#97]
great app, now missing filenames, search doesn't return all files containing string

**Comment by chtaylo2** [comment]
Thanks. "Missing filenames" is being addressed here: https://github.com/chtaylo2/Roku-GooglePhotos/issues/91.

Search not containing all files containing string might be due to this bug: https://github.com/chtaylo2/Roku-GooglePhotos/issues/89   

Both #91 and #89 are being addressed in an upcoming release. v2.1

**Comment by chtaylo2** [comment]
Release v2.1 submitted to Roku for publishing. Should see it soon.

**Comment by tonylang26** [comment]
A great feature you may consider for your already terrific slideshow app:

On ROKU push a button (A or B) during a shuffled slideshow to instantly switch
the flow order from shuffle to sequential (per sort order) without leaving the
current slide. Causing the next image to be not the next image in the shuffle
order, but the next sequential image and it will continue sequentially until
the toggle button is again pushed which will return the flow order to the
shuffle sequence again without ever leaving the ongoing slideshow. Why?
Shuffle is entertaining and is my preferred mode but I often encounter images
of interest (memory, affection curiosity etc.) during shuffle flow that makes
me want to see the sequence of which that image is a part. Most images are
taken in a sequence in time which links them in place and memory. Toggling
between these two modes in real-time would be fabulous. 

Thanks, and keep up the good work.

------ Original Message ------
Received: Wed, 28 Feb 2018 11:34:21 PM EST
